### ISSUE TITLE
building in jenkins

### ISSUE THREAD

**Issue by rimmartin** [cctbx/cctbx_project#10]
I'm building with 
python bootstrap.py
from within a jenkins job and it errors on the python not having the ssl module

```
Installing Python...
  log file is /var/lib/jenkins/workspace/cctbx/cctbx/base_tmp/Python_install_log
  getting package Python-2.7.8_cci.tar.gz...
    downloading from http://cci.lbl.gov/cctbx_dependencies : 14.3 MB
    [0%.........20%.........40%.........60%.........80%.........100%]
  installing Python-2.7.8_cci.tar.gz...
Using Python: /var/lib/jenkins/workspace/cctbx/cctbx/base/bin/python
  verifying Python installation in /var/lib/jenkins/workspace/cctbx/cctbx/base/bin/python OK
  verifying zlib installation in /var/lib/jenkins/workspace/cctbx/cctbx/base/bin/python OK
  verifying _ssl installation in /var/lib/jenkins/workspace/cctbx/cctbx/base/bin/pythonTraceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named _ssl



********************************************************************************

This python does not have _ssl - Secure Socket Library installed

********************************************************************************



Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1450, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 200, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 630, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 722, in build_python
    self.set_python(op.abspath(python_exe))
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 395, in set_python
    self.check_python_dependencies()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 387, in check_python_dependencies
    raise e
RuntimeError: Call to '/var/lib/jenkins/workspace/cctbx/cctbx/base/bin/python -c 'import _ssl'' failed with exit code 1
===== Running in modules: extracting files from clipper.gz

  removing .pyc files in /var/lib/jenkins/workspace/cctbx/cctbx/modules
  removed 0 files
===== Running in .: base
Process failed with return code 1
```
anyone run into this?  Is there a work around?

**Comment by Anthchirp** [comment]
What OS and version are you running?
We routinely run bootstrap.py in Jenkins on RHEL 6 without any issues.

**Comment by rimmartin** [comment]
ver. 1.641 Jenkins runs on CentOS 5 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux and the build is failing on comrade rhel 5 2.6.18-339.el5 #1 SMP Mon Aug 27 15:42:17 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux

It may perhaps be our security settings and causes the error to happen.

**Comment by Anthchirp** [comment]
I think CentOS/RHEL 5 may be the culprit here. We have no local build machines with RHEL 5 here, but there is one at LBL. Maybe one of them know more about this?
All I know is that there are also some tests failing on RHEL 5 the cause of which we never identified.  (Good news is that CentOS 5 support ends in March '17 anyway)

**Comment by bkpoon** [comment]
You will need to install the OpenSSL headers so that Python builds with SSL support. On CentOS 5, the package should be called openssl-devel. As root you would type "yum install openssl-devel".

**Comment by rimmartin** [comment]
I finally got sys admin to add the openssl-devel and am passed this this error.  There may be another error I'm testing on a CentOS 6 developer box I'm on before trying again with Jenkins.  Had built before on ^ and in the svn days I hade built on CentOS 5 & 6 and Ubuntu 14.   But I'm glad to be working with this github repository

**Comment by rimmartin** [comment]
Yes passed this
