### ISSUE TITLE
Use cbflib from github?

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#12]
It was mentioned that currently we use the [sourceforge version of cbflib](https://sourceforge.net/projects/cbflib/) and not the [github version of cbflib](https://github.com/yayahjb/cbflib).

Two parts to this issue:
* Do we want to move to the github version?
* If so, make changes so that new installations use the github version

**Comment by Anthchirp** [comment]
Further background to this: I currently understand the sourceforge version to basically be the stable branch of the github version.

**Comment by graeme-winter** [comment]
If I understand correctly, I think we should be using the version of CBFlib from github now, because Herbert said so in a recent email so I think we should make this so

If we are worried perhaps we should make a bootstrap_test which uses this in 1st instance to shake out any problems then merge this back to main bootstrap? That way we can test it & make sure no bad things happen.

Will also want to get developers to change over the source dir too... instructions to do this cleanly would be welcome :)

**Comment by phyy-nx** [comment]
Hi folks, I'll make a cbflib_to_git branch in the cctbx_project repository
with the change to git and run the tests using the branch on our local
build machines.  After any issues are resolved, I'll then merge the
branch.  I anticipate being able to do this late February.

Developers will only need to delete their local cbflib directory and then
re-run bootstrap, presuming they have no local edits to cbflib.  I'll send
an email to the cctbxbb detailing this when I merge the branch.

Does this sound reasonable?
-Aaron

**Comment by Anthchirp** [comment]
### Changing repositories

to get a fresh cbflib repository:
```
CBFLIB=$(libtbx.find_in_repositories cbflib)
rm -r "$CBFLIB"
git clone git@github.com:yayahjb/cbflib.git "$CBFLIB"
```

to get a cbflib repository with uncommitted changes in current svn repository copied over:
```
CBFLIB=$(libtbx.find_in_repositories cbflib)
cd $CBFLIB/..
mv cbflib cbflib.svn
git clone git@github.com:yayahjb/cbflib.git cbflib
cd cbflib.svn
svn diff > ../cbflib-patches
[ "$(uname)" != "Darwin" ] && svn status | grep "^\?" | cut -c 9- | xargs -I {} cp --parents -av {} ../cbflib
# This will copy over any unversioned files. This will unfortunately not work on macs.
cd $CBFLIB
patch -p0 < ../cbflib-patches
git status
```
In this case I recommend running a ```make clean``` afterwards.

**Comment by Anthchirp** [comment]
I ran tests on my local machine for cctbx, dials, xia2, and they ran fine. Jenkins should pick up new source of cbflib in tomorrow's builds. If there are any errors I'll open separate tickets.

**Comment by Anthchirp** [comment]
No errors seen. All tests passed. Transition completed.
