### ISSUE TITLE
rstbx: replace plugin mechanism with entry points?

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#138]
So [rstbx's frame.py has a plugin mechanism](https://github.com/cctbx/cctbx_project/blob/master/rstbx/slip_viewer/frame.py#L59-L69). ~~But it isn't used. And it is not implemented in a portable way, breaking the image viewer in the CCP4 Windows distribution.~~

~~Unless there are any objections I will remove it.~~

**Comment by Anthchirp** [comment]
(Because this code is not used if there are any objections I will still disable it, and suggest using the Python standard method of entry points instead.)

**Comment by Anthchirp** [comment]
@idyoung I suspect you have an opinion on how we should proceed with this?

**Comment by phyy-nx** [comment]
Hi, first off, the code is written to be as portable as possible, so I don't know what you mean.  We used standard libtbx path searching and os.path.join.  If libtbx.env.dist_path is broken on the ccp4 windows distribution, isn't that a different bug report?

Second, we use this functionality for certain xfel projects where we haven't checked in our plugin into the main repo.  The code cannot be deleted.

Could you check if using libtbx.env.find_in_repositories("rstbx") instead solves the problem?

**Comment by dagewa** [comment]
For the record, libtbx.env.dist_path works for me on the CCP4 Windows test computer

```
>>> libtbx.env.dist_path("rstbx")
'c:\\ccp4-7\\7.0\\lib\\py2\\site-packages\\cctbx_project\\rstbx`
```

**Comment by Anthchirp** [comment]
libtbx env is set at configuration time and not relocatable. In a CCP4 installation this may not reflect the actual location. Sometimes it does, as @dagewa just wrote, sometimes it does not. No idea why, but also not inclined to find out. 

Better approach would be to determine the path not via libtbx.env but the python module system directly (as we do [elsewhere](https://github.com/dials/dials/blob/master/conftest.py#L29)):
```
import rstbx
slip_viewer_dir = os.path.join(os.path.dirname(rstbx.__file__), 'slip_viewer')
```

However it is not clear to me *how* you use this code. Any plugins must live inside the ```slip_viewer``` directory, so do you inject these files there? Or do you write into the class.plugins dictionary? (In which this particular code would not be required)

(In any case this plugin pattern requires importing every potential plugin whether it is used or not. Using python entry points is much cleaner, so I will keep bringing that up 😃.)

**Comment by Anthchirp** [comment]
For the record this is what the user reported:
```
Traceback (most recent call last):
  File "C:\CCP4-7\python2.7\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\CCP4-7\python2.7\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dials\command_line\image_viewer.py", line 202, in <module>
    runner()
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dials\command_line\image_viewer.py", line 139, in __call__
    self.view()
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dials\command_line\image_viewer.py", line 147, in view
    reflections=self.reflections)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dials\util\image_viewer\spotfinder_wrap.py", line 34, in display
    reflections=reflections)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\dials\util\image_viewer\spotfinder_frame.py", line 46, in __init__
    super(SpotFrame, self).__init__(*args, **kwds)
  File "C:\CCP4-7\7.0\lib\py2\site-packages\cctbx_project\rstbx\slip_viewer\frame.py", line 63, in __init__
    contents = os.listdir(slip_viewer_dir)
WindowsError: [Error 3] The system cannot find the path specified: 'c:\\ccp4-7\\7.0\\lib\\checkout\\cctbx-phaser\\cctbx_project\\rstbx\\slip_viewer/*.*'
```
and you can see the true rstbx path diverging from the libtbx-assumed path in the traceback

**Comment by Anthchirp** [comment]
...about **python entry points**. [This blog post explains the concept really well, and definitely better than I can](http://amir.rachum.com/blog/2017/07/28/python-entry-points/). Please give it a go.

We need only a tiny modification from that, because we don't bother with standard ```setup.py```s in libtbx land. So instead of listing plugin classes or functions in ```setup.py``` we register them in ```libtbx_refresh.py```. Like this:
```python
import libtbx.pkg_utils
libtbx.pkg_utils.define_entry_points({
  'futuretbx.entrypoint': [
    'versionthingy=dials.util.version:dials_version',
  ]
 })
```
and after running ```make reconf```, or ```libtbx.configure```, or whatever else it is we do, we can use them like this:
```python
import pkg_resources
plugins = {}
for entry_point in pkg_resources.iter_entry_points('futuretbx.entrypoint'):
  plugins[entry_point.name] = entry_point.load()
print(plugins['versionthingy']())
```
which prints ```DIALS 1.dev.2036-g250153f```, or whatever your version is. In other words ```plugins['versionthingy']``` points to the function (class / thing with name) ```dials_version``` from ```dials.util.version```. The beauty of it is that these can be defined in different places, so the imaginary package ```junktbx``` can add 50 further names to this entry point without any issues, they can come from real files sitting in some directory, from C++ function names, or from python files of a module sitting in a .zip file. It doesn't matter where they sit, it doesn't matter what the source module is called, and the list of plugins is available everywhere under the same name. And that python module bringing in those 50 further names can be a libtbx module thingy or even a real pypi package. So suddenly it becomes possible to install plugins using ```pip install```. [If the DIALS extension model goes anywhere, this is where it is headed.](https://github.com/dials/dials/issues/257)

And you can obviously expand on it in a number of ways. You can make the importing action lazy by not calling ```.load()``` immediately. You can have plugins enumerated on configuration time, rather than at development time, etc. etc.

**Comment by phyy-nx** [comment]
Thanks for the writeup Markus.  Very cool stuff.  And yes, when we've been using the rstbx/slip_viewer plugin mechanism we've been softlinking the plugin file into this directory, so a better approach would be useful.

For reference, @dagewa found the root cause for the original bug report was elsewhere, which lessens the urgency of this issue.

**Comment by Anthchirp** [comment]
Yes, I've just seen that. Good detective work. Would not have expected that to affect libtbx.env in this manner...
:1


-- 
This e-mail and any attachments may contain confidential, copyright and or privileged material, and are for the use of the intended addressee only. If you are not the intended addressee or an authorised recipient of the addressee please notify us of receipt by returning the e-mail and do not use, copy, retain, distribute or disclose the information in or attached to the e-mail.
Any opinions expressed within this e-mail are those of the individual and not necessarily of Diamond Light Source Ltd. 
Diamond Light Source Ltd. cannot guarantee that this e-mail or any attachments are free from viruses and we cannot accept liability for any damage which you may sustain as a result of software viruses which may be transmitted in or with the message.
Diamond Light Source Limited (company no. 4375679). Registered in England and Wales with its registered office at Diamond House, Harwell Science and Innovation Campus, Didcot, Oxfordshire, OX11 0DE, United Kingdom

**Comment by Anthchirp** [comment]
feel free to reopen if there is interest in this
