### ISSUE TITLE
prime: CTRL+C does nothing

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#139]
Well, not nothing, but it certainly doesn't stop things.

Steps to reproduce: ```prime.run some.phil``` until these lines appear:
```
 int-0-(..).pickle h,k,l      ==> CC:  0.26
```
press CTRL+C, observe prompt floating past while ```n-1``` prime background processes continue churning out output.

**Comment by monarin** [comment]
Single-node Prime uses libtbx.easy_mp (https://github.com/cctbx/cctbx_project/blob/master/libtbx/easy_mp.py). This module wraps Python pool.map which is a blocking call. To catch KeyboardInterrupt or Ctrl-C, the module probably needs map_async and proper signal handling. Unless any changes applied to the easy_mp, this behavior will continue.

**Comment by monarin** [comment]
Per @phyy-nx suggestion, pool_map was replaced with parallel_map. See commit 39adfa20f865e240eb38a54b6a82fd889a59cd51.
