### ISSUE TITLE
bootstrap.py option to set github revision, tag or branch

### ISSUE THREAD

**Issue by rimmartin** [cctbx/cctbx_project#14]
The current options appear to limit the build to the master tip.  Is there a way to build a clone from a specific date or revision?

Also the options that do appear from 
```
python2.7 bootstrap.py --help
```
refer often to svn stuff

**Comment by Anthchirp** [comment]
There is no such option at this time. It raises the issue of how to deal with the number of repositories we have. Eg. to build a historic revision of dials you would need to pick revisions or branches for at least the cctbx_project repository and the dials repository.
(For DIALS releases [we do exactly this, and branch and/or snapshot everything](https://github.com/dials/cctbx/commit/5728324a17929625235b1ac813981f7a5aac532f).)

The number of repositories is also the reason why there are still SVN parameters. While not relevant for cctbx_project itself a lot of dependencies still live in SVN. This is unlikely to change anytime soon.

If this is for local development I would recommend running bootstrap for the builder you want, then picking out branches on the modules directory as you need them, and then rebuilding by running _make reconf_ in the _build_ directory.
If you want to create stable branches for releases you could follow the DIALS approach and rewrite bootstrap within the stable branches.

**Comment by rimmartin** [comment]
Hi @Anthchirp, I can see and appreciate the difficulty:-)

I can work without this so not a priority for me
