### ISSUE TITLE
Move libtbx.pkg_utils.require out of libtbx.configure/refresh

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/cctbx_project#151]
# Summary

libtbx.pkg_utils.require is currently being used to install via pip the packages mock, pytest, orderedset, Jinja2 and procrunner. This is done by the libtbx_refresh.py scripts in cctbx_project, dials and xia2.  In bootstrap, this is triggered in the build step as part of configuration before compilation.  It needs to instead be done in install_base_packages as part of the base step.

# Background
This issue comes from supercomputing environments where cctbx based software must be compiled on a node without internet access or without write privileges to the base folder.  

### Example use case
The user logs into a public node on a supercomputing environment and uses bootstrap.py to run hot and update.  The system provides a custom python with a cluster-dependent MPI package, optimized for their environment.  From the public node, the user logs into a compute node that is internet firewalled and has a different set of compilers as the public node.  The user runs 

```python bootstap.py build --with-python=`which python` ```

but it hangs because a) the user can't download mock, pytest etc. and b), even if they could, they couldn't install them because they lack write access to the system python.

### Conda
This issue is further complicated by conda installations of cctbx-based packages.  XFEL builds at LCLS have moved to conda exclusively.  Quoting the [conda docs](https://conda.io/docs/user-guide/tasks/manage-pkgs.html):

> Pip packages do not have all the features of conda packages, and we recommend first trying to install any package with conda. If the package is unavailable through conda, try installing it with pip. The differences between pip and conda packages cause certain unavoidable limits in compatibility, but conda works hard to be as compatible with pip as possible.

# Proposed change

New set of changes based on discussion 03/16/18

Specifically:

- [ ] Add two checks in libtbx.pkg_utils.require before running pip.  If the install is 'baseless', meaning there is no base folder and a different python is being used, do not try to install the specified package.  Likewise if the environment variable LIBTBX_NO_NETWORK is set, skip installation.  In both cases, print a warning that the package is missing and any code depending on it will not run. Owner: @Anthchirp
- [ ] Change scipy builder in install_base_packages.py to use pip instead of ./configure and make.  This works around fortran compiler issues.  Owner: @phyy-nx
- [ ] Add mock, pytest, orderedset, Jinja2, procrunner and scipy to the appropriate builders in install_base_packages. Owner: @phyy-nx

Feedback on this issue is appreciated :)

**Comment by graeme-winter** [comment]
OK, some thoughts - 
 - if you have a baseless install, how will installing dependencies in base step help?
 - not aware of your conda based installation, but most installations are not conda based
I think we need more information here - though chucking ticket comments around is probably not the way forwards.... it also seems a bit "specialist" trying to modify the build process to work on an air-gapped machine - is it really impossible to get a build machine which has the right environment on it? Re: permissions - surely this would make it almost impossible to install anything unless you are using virtualenv?

=> I think there is value in having a chat about this, as I don't fully understand at the moment...

**Comment by graeme-winter** [comment]
Subsequent discussion outcomes -
 - leave in this feature
 - add packages to base install
 - if baseless, have require() say sorry no can do
 - offer LIBTBX_NO_NETWORK env var which will prevent & say sorry no can do

@phyy-nx to liaise re: adding packages, east team to do other two things

**Comment by phyy-nx** [comment]
Tasks updated and owners assigned (@Anthchirp  and @phyy-nx).

**Comment by Anthchirp** [comment]
This should change require() to more or less no-op on base-less builds. I wouldn't call the environment variable ```LIBTBX_NO_NETWORK``` as I think that name is misleading. How about ```LIBTBX_DISABLE_UPDATES```?

**Comment by graeme-winter** [comment]
+1 to better name, I like this a lot

**Comment by graeme-winter** [comment]
Turns out the agreement on this being appropriate was not universal, and that this is still a problem. Reopening.

**Comment by Anthchirp** [comment]
Agreed in today's meeting that the solution for the Windows package is to update it.

**Comment by graeme-winter** [comment]
To confirm then @bkpoon @nksauter @phyy-nx @Oeffner this current approach is agreed to be satisfactory modulo Windows update?

**Comment by Oeffner** [comment]
Yes. I'll get around to update the python bundle this week for 64 bit builds on Windows.
