### ISSUE TITLE
When creating flex array from Python, allow option to not init values to 0

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/cctbx_project#156]
i.e. if I make a flex.double which I will fill with values later, I don't want to spend time writing 0's which will be over written

**Comment by graeme-winter** [comment]
Also in C++ code, init with null functor thinger like:

```
  scitbx::af::shared<int>
  read_uint16(boost_adaptbx::python::streambuf & input,
              size_t count)
  {
    scitbx::af::shared<int> result;
    boost_adaptbx::python::streambuf::istream is(input);
    std::vector<unsigned short> data;
    data.resize(count);

    is.read((char *) &data[0], count * sizeof(unsigned short));

    for (size_t j = 0; j < count; j++) {
      result.push_back((int) data[j]);
    }

    return result;
  }
```

**Comment by rjgildea** [comment]
I'm not convinced of the need for this:
1) You don't want to be initialising a flex array and iterating over it in Python if you're interested in speed.
2) If you have the design pattern a) create flex array, b) pass flex array by reference to C++ function which fills in values - then perhaps it would be better to modify the C++ function to instead take care of creating the array and returning a new array.

**Comment by graeme-winter** [comment]
Second comment I made though, in a lot of places we're not using the null init option anyway from C++ too.

**Comment by rjgildea** [comment]
That's a different problem though!

**Comment by graeme-winter** [comment]
Also, you are saying here we _should not allow_ people not to init values? 🤔

**Comment by rjgildea** [comment]
Does numpy (for example) have such a feature (genuine question)?

**Comment by graeme-winter** [comment]
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.empty.html

yes

**Comment by graeme-winter** [comment]
Since no interest and (potentially) a fundamental / low level change...
