### ISSUE TITLE
cctbx.crystal.reindex.reindexing_operators() sometimes fails

### ISSUE THREAD

**Issue by keitaroyam** [cctbx/cctbx_project#18]
Here is the code to reproduce the problem:
<pre>
from cctbx.crystal import reindex
from cctbx import crystal
xs1=crystal.symmetry((40.3,81.7,199.9,93.2,95.7,104.1), 1)
xs2=crystal.symmetry((40.1,81.4,189.6,92.6,89.0,103.8), 1)
reindex.reindexing_operators(xs1, xs2)
</pre>
and we get:
<pre>
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    reindex.reindexing_operators(xs1, xs2)
  File "cctbx_build/src/cctbx/crystal/reindex.py", line 59, in __init__
    try: common_lattice_group.expand_smx(s)
AttributeError: 'NoneType' object has no attribute 'expand_smx'
</pre>

Clearly we need `break` after replacing common_lattice_group with None https://github.com/cctbx/cctbx_project/blob/master/cctbx/crystal/reindex.py#L61

I will commit this if nobody objects.

**Comment by Anthchirp** [comment]
instead of
```
      for s in lat_sym_2.build_derived_acentric_group().change_basis(
        self.similarity_cb_op ):
        try: common_lattice_group.expand_smx(s)
        except RuntimeError:
          common_lattice_group=None
          break
```
I'd rather say
```
      try:
        for s in lat_sym_2.build_derived_acentric_group().change_basis(
          self.similarity_cb_op ):
          common_lattice_group.expand_smx(s)
      except RuntimeError:
        common_lattice_group=None
```

But I don't know what this code is doing, so can't comment on the actual issue at hand.

**Comment by keitaroyam** [comment]
Thanks for your comment. It would make the lines shorter, but I prefer simple `break` to make where RuntimeError could happen clear.

(In this case "Non-crystallographic rotation matrix encountered" is thrown in sgtbx::space_group::add_smx() called from expand_smx() because the operator s is incompatible with lat_sym_1)
