### ISSUE TITLE
dxtbx test broken

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#187]
As we know converting tests to pytest means an implicit code review, which presents an opportunity to identify broken tests. Today's victim is ```tst_image_reader.py```. It looks like most of the tests were disabled last year - no doubt due to the lack of fine grained test execution control in the libtbx testing environment.

https://github.com/cctbx/cctbx_project/blob/07d12364fb48b5d582dc12443706adc5fe17b991/dxtbx/tests/tst_image_readers.py#L384-L396

Re-enabling the tests fails, so some work is required there

**Comment by jmp1985** [comment]
Fixed tests in commit eb066297c23744986b0f4c4415191754d9825cd9
