### ISSUE TITLE
Windows Python updates

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#190]
Hi Rob,

can we please have Python 2.7.15 and procrunner 0.6.1 for the next Windows Python package.

Many thanks

**Comment by Oeffner** [comment]
@bkpoon 
Hi Billy

I have put a new 2.7.15 bundle for Windows on cci with procrunner 0.6.1 and matplotlib 2.0.0. It lives in rdo20@cci.lbl.gov:Python2.7.15_x86_64_plus_relocatable.zip if you could copy that to the download website.

Thanks

Rob

**Comment by bkpoon** [comment]
Thanks, Rob! I just moved the file.

--
Billy K. Poon
Research Scientist, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
1 Cyclotron Road, M/S 33R0345
Berkeley, CA 94720
Tel: (510) 486-5709
Fax: (510) 486-5909
Web: https://phenix-online.org

**Comment by Anthchirp** [comment]
Confirmed deployed. Many thanks
