### ISSUE TITLE
how do we deal with dxtbx -> dials dependencies?

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#193]
There are currently places in dxtbx where dxtbx depends on dials code, and will fail if dials is not available.
The Jenkins test in pull request https://github.com/cctbx/cctbx_project/pull/186 fails due to dials not being available in the test environment. The pytest conversion in the pull request exposed this import:
https://github.com/cctbx/cctbx_project/blame/70bb98d43eca91908e54daa9df9712c72ae48558/dxtbx/format/FormatMultiImage.py#L164

In some places we ```import from dials``` and handle ```ImportErrors```. In other places we do not handle these gracefully:
```python
$ grep "from \+dials" -C 1 -R .
command_line/detector_superpose.py-    ''' Set the expected options. '''
command_line/detector_superpose.py:    from dials.util.options import OptionParser
command_line/detector_superpose.py-    import libtbx.load_env
--
command_line/detector_superpose.py-if __name__ == '__main__':
command_line/detector_superpose.py:  from dials.util import halraiser
command_line/detector_superpose.py-  try:
--
format/FormatCBFFullPilatusDLS6MSN100.py-    #avoid a module-level import from the DIALS namespace that kills LABELIT
format/FormatCBFFullPilatusDLS6MSN100.py:    from dials.util.masking import GoniometerShadowMaskGenerator
format/FormatCBFFullPilatusDLS6MSN100.py-
--
format/FormatCBFFullPilatusDLS6MSN100.py-
format/FormatCBFFullPilatusDLS6MSN100.py:      from dials.util.masking import GoniometerShadowMaskGenerator
format/FormatCBFFullPilatusDLS6MSN100.py-      from scitbx.array_family import flex
--
format/FormatCBFMiniPilatusDLS6MSN100.py-  def get_goniometer_shadow_masker(self, goniometer=None):
format/FormatCBFMiniPilatusDLS6MSN100.py:    from dials.util.masking import GoniometerShadowMaskGenerator
format/FormatCBFMiniPilatusDLS6MSN100.py-    from scitbx.array_family import flex
--
format/SmarGonShadowMask.py-
format/SmarGonShadowMask.py:from dials.util.masking import GoniometerShadowMaskGenerator
format/SmarGonShadowMask.py-
--
format/FormatCBFFullPilatusDLS300KSN104.py-
format/FormatCBFFullPilatusDLS300KSN104.py:    from dials.util.masking import GoniometerShadowMaskGenerator
format/FormatCBFFullPilatusDLS300KSN104.py-    from scitbx.array_family import flex
--
format/FormatCBFMiniPilatusDLS12M.py-  def get_goniometer_shadow_masker(self, goniometer=None):
format/FormatCBFMiniPilatusDLS12M.py:    from dials.util.masking import GoniometerShadowMaskGenerator
format/FormatCBFMiniPilatusDLS12M.py-    from scitbx.array_family import flex
--
format/nexus.py-    def make_mask(dset):
format/nexus.py:      from dials.array_family import flex
format/nexus.py-      mask_data = flex.int(dset[()]) == 0
```

How should we deal with this in general?

**Comment by Anthchirp** [comment]
Discussed with @jmp1985 and fixed the immediate issue holding up #186 in 8702394436724eb3db5b25dbc200acc9a44e39aa.

**Comment by rjgildea** [comment]
The GoniometerShadowMaskGenerator itself has some other dependencies on other dials code, which would also need to be moved to dxtbx if we wanted to completely remove any dxtbx -> dials dependency. Not sure if they really belong in dxtbx... 
```
    from dials.util.ext import is_inside_polygon
    from dials.util.ext import mask_untrusted_polygon
```

**Comment by graeme-winter** [comment]
Guess this is a symptom of the wider problem of circular dependencies. Without pulling the whole of dials into dxtbx I do not see a simple solution.

Some of these are easy fixes though e.g. using the simplest flex array possible (i.e. not importing from dials.array_family if scitbx.array_family would do the job.)

**Comment by Anthchirp** [comment]
guess the original question is thus answered
