### ISSUE TITLE
Add pickling support for scitbx.sparse matrices

### ISSUE THREAD

**Issue by rjgildea** [cctbx/cctbx_project#195]
Currently scitbx.sparse matrices are not pickleable, which means they can't be returned by libtbx.easy_mp.parallel_map. This would be useful in several parts of DIALS, e.g. dials.refine, dials.cosym, and scaling.

See e.g.:
https://github.com/dials/dials/blob/master/algorithms/refinement/refiner.py#L597
(multiprocessing currently disabled if SparseLevMar refinement engine selected)

https://github.com/dials/dials/blob/master/algorithms/symmetry/cosym/target.py#L193
(currently uses scipy.sparse as that is pickleable)

Also @jbeilstenedmands would like to use it to parallelise his scaling code.

**Comment by dagewa** [comment]
+1 this would allow us to explore the use of multiprocessing non-linear least squares refinement for the XFEL case where the problem can be very sparse

**Comment by jbeilstenedmands** [comment]
This would be very helpful for me, there are several places in my scaling code where I do calculations that return large sparse matrices, and being able to parallelise this would be very helpful for performance.

**Comment by graeme-winter** [comment]
LBL folks - any objections to someone over this side taking a look at this?
