### ISSUE TITLE
Split datablocks not deserialized correctly when using check_format=False

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/cctbx_project#203]
See daf39d27a45ab62b68703495b89c550bd8a3564a, which is a test to show this problem (currently marked as expected to fail).

The test reads an hdf5 file as a datablock, splits it so the datablock contains one image, then serializes the datablock.  Deserializing the datablock with check_format=True works fine.  The single file indices array, which tracks which images are in the datablock, is correctly read from the json.  However, check_format=False does not correctly deserialize the array.  This affects all cases of check_format=False, notably in dials.split_experiments and dials.combine_experiments.

When bug is fixed, pytest.mark.xfail can be removed

**Comment by graeme-winter** [comment]
Nice use of pytest Aaron! 👍

This is exactly where it wins out

**Comment by phyy-nx** [comment]
Fixed by #209
