### ISSUE TITLE
Is it valid to have a Scan with zero oscillation range?

### ISSUE THREAD

**Issue by dagewa** [cctbx/cctbx_project#208]
Related to #206. This has triggered some discussion. What does it mean for a `Scan` to have zero oscillation?

One use case that was suggested is simply to carry around the rotation offset between multiple still images that were collected using a goniometer. The thought was that the `Goniometer` object does not carry the information required to represent this case and we would need a `Scan` for each crystal, with different start angles. However, this is not true because `Goniometer` objects have a `fixed_rotation` matrix that is intended to capture this case. If that was used, a series of stills do not need multiple `Scans`, but would have a `Goniometer` for each image, which differ by their **F** matrix.

Please comment on this ticket saying which design you prefer, and why.

An adjunct issue to this one is the failure of `dxtbx.print_header labelit_regression/detectors/200mMNaCl5pcGlyc_400.edf` when zero oscillation scans were briefly disallowed, fixed again in e58dbf82. The relevant format class, FormatEDFALS733, [hardcodes](https://github.com/cctbx/cctbx_project/blob/master/dxtbx/format/FormatEDFALS733.py#L75) a zero width `Scan`. @nksauter is this just to produce a dummy `Scan` object where there is incomplete metadata in the image header?

**Comment by jmp1985** [comment]
For purely practical reasons, I think it is better to have the Scan containing the starting angle with rotation angle equal to zero. 

If the gonioneter encodes the rotation in the form of the fixed rotation then it means that all the goniometer objects will be different for each image. With the rotation being in the scan object, the goniometer objects will then all be the same and can be shared between the images.

**Comment by nksauter** [comment]
There's nothing magical about ALS 7.3.3 data--it is a SAXS/WAXS/GiSAXS beam
line and I've never received any data that formed a rotation series.  My
only interest here is to be able to read the test image without getting a
RuntimeError.  I have no specific use case that requires a scan.

However I agree with Aaron & Parkhurst that oscillation==0 makes sense as a
recognized condition.

Nick

**Comment by dagewa** [comment]
Thanks folks, closing this now. Scans will continue to allow the edge case of a "still scan".
