### ISSUE TITLE
License

### ISSUE THREAD

**Issue by merkys** [cctbx/cctbx_project#213]
I can not find any information about the licensing of cctbx. It would be nice if the project included LICENSE file and/or a section for it in its documentation.

**Comment by graeme-winter** [comment]
inside the cctbx_project/cctbx folder there is LICENSE_2_0.txt - which appears in several other folders. It is a BSD-type variant.

I do however agree that either (i) individual projects need their own repositories with clear license files or (ii) there needs to be one single universal license file at the root of cctbx_project. This requirement as it is clearly impossible to check out only subsets of the code => the license should be the same for everything checked out. 

Calling the license file by a conventional name for GitHub projects would probably also be polite. 

I guess the owners of each of the sub-projects should chime in here with opinions as to which of (i) or (ii) would be appropriate, or offer alternative solutions.

**Comment by merkys** [comment]
Thank you for pointing out the license file for me. Either option (i) or (ii) would help the users of the code, as of now it's not clear what one can/can't do with pieces of code in this repository.

In option (i) sub-projects do not necessary have to be placed in separate repositories, only license files for each of the sub-projects need to be added. However, splitting off sub-projects with less free licenses would save some effort for users willing to have more freedom of using the source.
