### ISSUE TITLE
FormatMultiImage.py broken for VMXi nxs - AssertionError: No lazy support for sweeps

### ISSUE THREAD

**Issue by rjgildea** [cctbx/cctbx_project#215]
Download the VMXi example dataset from here:
https://zenodo.org/record/1195871#.Wy0duK2RC00

```
$ dials.import ~/Downloads/image_1508.nxs 

############################################################################
#                                                                          #
# The DIALS reference paper has now been published:                        #
#                                                                          #
# DIALS: implementation and evaluation of a new integration package (2018) #
# https://doi.org/10.1107/S2059798317017235        Acta Cryst. D74, 85-97. #
#                                                                          #
############################################################################


DIALS 1.dev.2656-g9da46fc
The following parameters have been modified:

input {
  datablock = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatNexus.FormatNexus'>
  num images: 600
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing datablocks to datablock.json
$ dials.show datablock.json 

############################################################################
#                                                                          #
# The DIALS reference paper has now been published:                        #
#                                                                          #
# DIALS: implementation and evaluation of a new integration package (2018) #
# https://doi.org/10.1107/S2059798317017235        Acta Cryst. D74, 85-97. #
#                                                                          #
############################################################################


Sorry: Unable to handle the following arguments:
  "datablock.json" failed during DataBlock processing:
    Traceback (most recent call last):
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/dials/util/options.py", line 306, in try_read_datablocks
        self.datablocks.append(converter.from_string(argument))
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/dials/util/phil.py", line 47, in from_string
        check_format=self._check_format))
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 969, in from_json_file
        directory=directory)
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 957, in from_json
        directory=directory)
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 944, in from_dict
        importer = DataBlockDictImporter(obj, check_format, directory)
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 651, in __init__
        self.datablocks = self._load_datablocks(obj, check_format, directory)
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 664, in _load_datablocks
        return [self._load_datablocks(dd, check_format, directory) for dd in obj]
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/datablock.py", line 762, in _load_datablocks
        format_kwargs = format_kwargs)
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/imageset.py", line 611, in make_sweep
        single_file_indices = range(*array_range))
      File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/dxtbx/format/FormatMultiImage.py", line 230, in get_imageset
        assert not (as_sweep and lazy), 'No lazy support for sweeps'
    AssertionError: No lazy support for sweeps
```

**Comment by rjgildea** [comment]
Commenting out this line make it work: https://github.com/cctbx/cctbx_project/blob/master/dxtbx/format/FormatMultiImage.py#L193

**Comment by rjgildea** [comment]
@phyy-nx could you comment on this as you added this line recently:
https://github.com/cctbx/cctbx_project/commit/86cd29c7b489e62d50b6ab7ece126082229ff3f0#diff-f47d4d93c67a22b04d3bd4e2b3b21afbR193

**Comment by phyy-nx** [comment]
First take is that it works for me.  dxtbx.print_header, dials.import and dials.image_viewer.  Verified my code is up to date including lazy=True on line 193 of FormatMultiImage.py.  Continuing to investigate.

$ dials.import image_1508.nxs

############################################################################
#                                                                          #
# The DIALS reference paper has now been published:                        #
#                                                                          #
# DIALS: implementation and evaluation of a new integration package (2018) #
# https://doi.org/10.1107/S2059798317017235        Acta Cryst. D74, 85-97. #
#                                                                          #
############################################################################


DIALS 1.dev.2657-g1518f32d1
/net/dials/raid1/aaron/dialsbuild/base/lib/python2.7/site-packages/h5py-2.7.0-py2.7-linux-x86_64.egg/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
The following parameters have been modified:

input {
  datablock = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatNexus.FormatNexus'>
  num images: 600
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing datablocks to datablock.json

**Comment by phyy-nx** [comment]
Ok, $ dials.show datablock.json does fail for me.  Looking into it.

**Comment by phyy-nx** [comment]
Thanks all.  As an aside, we need a small Eiger dataset in dials_regression so we can catch stuff like this.

**Comment by rjgildea** [comment]
Thanks for the fix, yes I agree we could do with an example dataset for dials_regression. @graeme-winter do you have any handy small VMXi datasets we could use?

**Comment by graeme-winter** [comment]
I'll come up with something though not on Friday evening - remind me Monday, got something somewhere...

**Comment by graeme-winter** [comment]
Oh, just remembered - 

https://zenodo.org/record/1195871
