### ISSUE TITLE
Update Boost to 1.56

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#23]
Issue to track boost 1.56 update.

DIALS 1.5 is now branched, so proceed when ready.

**Comment by luc-j-bourhis** [comment]
I would be more than happy to do it but I am not sure where I should copy boost.gz on cci.lbl.gov. Do I even have enough rights to do that?

**Comment by bkpoon** [comment]
I placed the standard boost_1_56_0.tar.gz file into
/net/cci-filer2/raid1/auto_build/repositories directory. The update would
just require changing the symbolic link for boost_hot.tar.gz. Also, for our
automated build system, we will update the boost_hot directory to be the
extracted copy of the tarball.

--
Billy K. Poon
Research Scientist, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
1 Cyclotron Road, M/S 33R0345
Berkeley, CA 94720
Tel: (510) 486-5709
Fax: (510) 486-5909
Web: https://phenix-online.org

**Comment by bkpoon** [comment]
Boost 1.56 is live and the tests have been updated. To update your installation, you must delete the "build" directory first, then run bootstrap.py.

```python
cd <installation directory>
rm -fr build
python bootstrap.py hot update build --builder=cctbx --nproc=#
```

**Comment by bkpoon** [comment]
No new problems seem to have popped up from the upgrade, so I'll close this issue.
