### ISSUE TITLE
Adding psutil as a dependency

### ISSUE THREAD

**Issue by bkpoon** [cctbx/cctbx_project#239]
We would like to add psutil (https://github.com/giampaolo/psutil) as a new dependency for CCTBX. The package is available through ```conda``` and ```pip```. This package provides cross-platform tools for getting information about processes and the system. This would make some of the tools in [libtbx/introspection.py](https://github.com/cctbx/cctbx_project/blob/master/libtbx/introspection.py) and [libtbx/utils.py](https://github.com/cctbx/cctbx_project/blob/master/libtbx/utils.py) more robust and consistent across platforms.

The functionality that is most relevant right now is the ability to get memory usage and the amount of available memory. For some cryo-EM tools, we would like to do this before trying to do certain tasks.

Thoughts and comments?

**Comment by graeme-winter** [comment]
I can see this being useful

**Comment by bkpoon** [comment]
Added dependency via 124d025497f2a882ac2603feaaab34a7b5929e04. Future commits can use ```psutil```.
