### ISSUE TITLE
new dxtbx tests has dependency on DIALS

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#246]
@phyy-nx, @nksauter 

The test you added in b689c313575db13cb10eb321374e6fdce3b48c10 currently fails the CCTBX/dxtbx tests as it introduces a dependency on DIALS (which is purposely not installed for the tests as DIALS is currently not a dxtbx dependency, for the wider discussion of whether DIALS should be a dependency see #193).
Specifically, it relies on the gaussian profile model which is a DIALS plugin to dxtbx.

I would suggest to either see if you can remove the dependency or alternatively move the test to the DIALS repository.

**Comment by rjgildea** [comment]
Looking at the test error logs, the problematic dependency is the guassian_rs_profile, which I don't think has any relevance on the actual thing being tested:
`ImportError: No module named dials.extensions.gaussian_rs_profile_model_ext`

As such, I think that removing the profile model from the experiments json encoded in the script should make the test pass without any dependency on DIALS:

```
$ git diff
diff --git a/dxtbx/tests/test_crystal_model_equivalence.py b/dxtbx/tests/test_crystal_model_equivalence.py
index 1362fc9ab..9de68e620 100644
--- a/dxtbx/tests/test_crystal_model_equivalence.py
+++ b/dxtbx/tests/test_crystal_model_equivalence.py
@@ -37,7 +37,6 @@ json_is = """{
       "beam": 0,
       "detector": 0,
       "crystal": 0,
-      "profile": 0,
       "imageset": 0
     }
   ],
@@ -194,19 +193,10 @@ json_is = """{
         -4.754762088402217,
         -2.934294620730966
       ],
-      "space_group_hall_symbol": "-C 2yc",
-      "ML_half_mosaicity_deg": 0.3692704083777256,
-      "ML_domain_size_ang": 416.04559892901716
-    }
-  ],
-  "profile": [
-    {
-      "n_sigma": 3.0,
-      "__id__": "gaussian_rs",
-      "sigma_m": 0.0,
-      "sigma_b": 0.14442609665641026
+      "space_group_hall_symbol": "-C 2yc"
     }
   ],
+  "profile": [],
   "scaling_model": []
 }"""
 
```

**Comment by phyy-nx** [comment]
Looks fixed.  Thanks.
