### ISSUE TITLE
xfel missing prime dependency

### ISSUE THREAD

**Issue by ndevenish** [cctbx/cctbx_project#247]
In `xfel`:
https://github.com/cctbx/cctbx_project/blob/9c0c21826614bf3694bc890019be6b089ef0bc89/xfel/clustering/singleframe.py#L10

But in `xfel/libtbx_config` `prime` isn't listed as a dependency:
https://github.com/cctbx/cctbx_project/blob/9c0c21826614bf3694bc890019be6b089ef0bc89/xfel/libtbx_config#L2-L3

**Comment by nksauter** [comment]
Aware of this, disagree that something needs to be done.

**Comment by ndevenish** [comment]
I disagree that nothing needs to be done.

Either:

- The dependency is required and is missing in this file
- The dependency is optional and is a) missing in this file and b) should be checked for in a `try: except ImportError:`
- The entire dependency system is broken and should be fixed or removed

Code inside dials depends on xfel code that depends on prime. Configuring a working distribution depends on magically knowing that this dependency is deliberately left out. Ergo, broken.

**Comment by Anthchirp** [comment]
The ```dials``` builder already includes ```prime``` and ```iota```:
https://github.com/cctbx/cctbx_project/blob/5a7a836f54187d217a86a9da2c2c1eb184e3c75a/libtbx/auto_build/bootstrap.py#L1813
Not sure why that is - ```dials``` uses neither.

**Comment by phyy-nx** [comment]
Users of dials doing serial crystallography use both

**Comment by phyy-nx** [comment]
Hi folks, the right thing to do is to abstract InputFrame out of prime.api since it's being used in multiple places.  Since prime depends on xfel it makes sense to put InputFrame into xfel, probably into xfel.ui.components.  Unless @monarin has an objection, I'll do that.
Thanks all.

**Comment by monarin** [comment]
No objection :) thank you.

**Comment by dagewa** [comment]
Hi all, this just caught out CCP4 while preparing to release DIALS 1.12.5. Hence reopening to discuss more complete solutions. The hidden dependency `dials.cosym`-->`xfel`-->`prime.api` means our cosym was broken, as only the modules _required_ for DIALS are built by CCP4. Currently, that means we get xfel, but not prime. Should 'prime' therefore be a required module of xfel, not merely optional? Or would it in fact be reasonable to refactor the [xfel/clustering/cluster.py](https://github.com/cctbx/cctbx_project/blob/master/xfel/clustering/cluster.py) code to avoid this dependency? The class that is the proximal obstacle is minimal: https://github.com/cctbx/cctbx_project/blob/1d33eaa9798357cf29243b50eb87e87feeaf71f4/prime/api.py#L7-L30

**Comment by dagewa** [comment]
@phyy-nx I note you say it is not practical to break the circular dependency `prime`<-->`xfel` by moving code. However I still think your proposal of moving `InputFrame` to `xfel` would help here, because I think this is the only thing that is tripping up `dials.cosym`. What do you think?

**Comment by phyy-nx** [comment]
Hi, sorry this fell off of my radar.  I'll do it later this week.

**Comment by phyy-nx** [comment]
@dagewa let me know if this commit does the trick. there's one more import of prime in xfel but it's in the xfel gui.

**Comment by dagewa** [comment]
Thanks! That seems to sort it. I just did a simple test by moving `prime/` aside and ensuring that `test_cosym.py` still works.
