### ISSUE TITLE
conda/pip

### ISSUE THREAD

**Issue by smsaladi** [cctbx/cctbx_project#253]
Is making cctbx available over conda or pip planned for the near (or far) future? I saw this old, open issue #9 and the label "hold for conda" as well as a few branches (that are pretty stale). Is this something you are looking for help to do?

**Comment by bkpoon** [comment]
Yes, but without a concrete timeline yet. The current effort is to use conda for dependencies first. Once CCTBX builds with conda dependencies, then we can work towards making CCTBX installable via conda.

One difference between conda and pip, which makes conda the primary target, is that we have non-Python dependencies. They are easily installable via conda, but would require compilation with pip.

**Comment by smsaladi** [comment]
Ah, I see -- thanks for all your efforts!

**Comment by Anthchirp** [comment]
see https://github.com/cctbx/cctbx_project/issues/9#issuecomment-671872829
