### ISSUE TITLE
lzw compression code

### ISSUE THREAD

**Issue by nwmoriarty** [cctbx/cctbx_project#254]
There is a module for lzw compression in libtbx. If no one outside eLBOW is using it, we are considering deleting it from the code base.

**Comment by graeme-winter** [comment]
I for one support the idea of keeping dependencies close to where they are needed

Minimising the dependencies of libtbx seems like a good thing to me. Gets my vote

**Comment by bkpoon** [comment]
I just checked in changes to make lzw.py run in Python 2 and 3. Feel free to move it when you're ready.
