### ISSUE TITLE
Please can we get bootstrap.py to check that dependencies present

### ISSUE THREAD

**Issue by graeme-winter** [cctbx/cctbx_project#26]
i.e. on macs sometimes /usr/include is not there so have no zlib.h etc, which causes build to fail (with good reason) - so checking if /usr/include exists if not fail would be useful...

**Comment by graeme-winter** [comment]
i.e. advise to run xcode-select --install

**Comment by nwmoriarty** [comment]
There is a check for zlib being in the python but it could be better.

**Comment by Anthchirp** [comment]
This could be a bit overzealous - no idea if other locations are permitted.
