### ISSUE TITLE
Add mrcfile as a dependency to iotbx

### ISSUE THREAD

**Issue by bkpoon** [cctbx/cctbx_project#263]
We would like to add [```mrcfile```](https://github.com/ccpem/mrcfile) as a new dependency for ```iotbx```. This package is for reading maps in MRC/CCP4 format and provides support for updated specifications to the format.

More work will be done to integrate the reading/writing functionality of ```mrcfile``` into ```iotbx``` and to determine if this package can replace our existing map reader from ```ccp4io```.

**Comment by dagewa** [comment]
Sounds good! I already use mrcfile to read image stacks. The use of memory mapping makes this feasible even for huge files.

**Comment by bkpoon** [comment]
Added dependency via 124d025497f2a882ac2603feaaab34a7b5929e04. Future commits can use ```mrcfile```.

**Comment by Oeffner** [comment]
We are doing nightly builds off Phaser and are now getting "import bz2" errors during a bootstrap build on Ubuntu 16 and 18 when it tries to build the mrcfile module. The system python on both OS do have the bz2 module present. Log from building the mrcfile module is http://www-structmed.cimr.cam.ac.uk/Local/PhaserNightly/Current_Ubuntu16.04_4.15.0-39-generic_gcc5.4.0_x86_64-linux-gnu/buildlog.txt 
Let me know if anyone has a suggestion for fixing this.

**Comment by graeme-winter** [comment]
Worth checking bz2 module not missing e.g. developer headers in 

```
/home/phaserbuilder/PhaserNightlyBuild/Current/base_tmp/Python_install_log
```

**Comment by Oeffner** [comment]
Thank you. I just installed libbz2-dev which were missing on both systems. Hopefully this will fix the problem.

**Comment by graeme-winter** [comment]
👍

**Comment by Anthchirp** [comment]
guess this is resolved and can be closed but not my call.
would suggest adding lines
```python
import libtbx.pkg_utils
libtbx.pkg_utils.require('mrcfile', '>=1.1')
```
to iotbx/libtbx_refresh.py to save having every developer with existing development installations figure out how to install new/updated dependencies.

**Comment by graeme-winter** [comment]
This can be closed or no?

**Comment by pcxod** [comment]
Just built cctbx [smtbx+iotbx] and getting runtime error when trying to use it:
ImportError('No module named mrcfile',) 

Is this an expected behaviour?

**Comment by graeme-winter** [comment]
Probably iotbx dependency

Should probably be optional like h5...

**Comment by pcxod** [comment]
Should it be just put into try/except?

**Comment by ndevenish** [comment]
If you are using bootstrap then it should have installed mrcfile; if using your own distribution then you need to install it manually.

If you don't use the features that it's relying on from mrcfile, then yes, it's probably safe to make it option in your local copy.

It looks like it'd be pretty easy to make optional, but it looks like it's just a python dependency so I don't think there is the justification (binary things like H5 are more complicated).

**Comment by pcxod** [comment]
Not much constructive - why any software would fail if it had not even envisaged to use this?

**Comment by graeme-winter** [comment]
I see the point 

```crystal_symmetry_from_any.py```

has

```
from iotbx.mrcfile import crystal_symmetry_from_ccp4_map as from_ccp4_map
```

where earlier

```
if (libtbx.env.has_module("ccp4io")):
  from iotbx.mtz import crystal_symmetry_from_mtz as from_mtz
else:
  from_mtz = None
```

if no mrcfile cannot import module - even if not using (my original issue here)

iotbx _should_ gracefully fail iff you try to access an mrc map - else should be fine

**Comment by graeme-winter** [comment]
Non-bootstrap is still valid build

**Comment by bkpoon** [comment]
Hi @pcxod, I checked with @terwill and committed a change that wraps that import with try/except (4c51c9c10f2d434d48f3e74e27496f3e522605e2). Please let us know if there are any more issues with `mrcfile` or any other problems from recent changes.

**Comment by pcxod** [comment]
Hi @bkpoon, thanks. This resolves the issue my build had.
