### ISSUE TITLE
Using a stable sort as default in flex.sort_permutation, flex.sort?

### ISSUE THREAD

**Issue by jbeilstenedmands** [cctbx/cctbx_project#288]
Recently I have been using some flex sorting code in DIALS, and after discovering some cross-platform variations in results I was surprised to find that the default is to use an unstable sorting algorithm. In the context of sorting, unstable means that any equal values in a list will not in general be in the same order as in the input list, and the order may be different across platforms based on the c++ compiler (however the sorting is still deterministic and will give the same value when repeated for given compiled code).

An unstable sort is the default for std::sort in c++: for scitbx it looks like the stable option was added in commit 7971e48 and then used for miller sets and arrays in commit d729566 , however the default was kept as False.

The benefit of an unstable sort is a potentially faster runtime, but given the nature of scitbx being a library, I was wondering if the default should be set as a stable sort, and in specific instances where it is safe and useful to do so then the stable=False option can be used? The flex.sort and flex.sort_permutation methods are used extensively throughout the codebase, so it is not clear where this could cause an issue.

In pure python, the standard sorting methods are stable, however numpy uses an unstable quicksort by default. If users are unaware that the cctbx default is unstable, this could lead to subtle and nasty bugs.

**Comment by phyy-nx** [comment]
Total agreement here.  Any identification of platform-specific degeneracy
that can be eliminated is worth eliminating.

**Comment by graeme-winter** [comment]
Practical suggestion:
 - run all tests, record timing (serial not parallel)
 - make change
 - run all tests again, record timing
 - if any times changed significantly, look at setting these to explicitly use unstable version
Opinions?
