### ISSUE TITLE
NeXus: get_detector_module_slices reads data dimensions backwards

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/cctbx_project#305]
In nexus.py, the function get_detector_module_slices is used to figure out how to slice the raw pixel data into panels.  However, I think this function is interpreting the NeXus specification wrongly.  Compare:

http://download.nexusformat.org/sphinx/classes/applications/NXmx.html

> data_origin: (required) NX_INT
> 
> A dimension-2 or dimension-3 field which gives the indices of the origin of the hyperslab of data for this module in the main area detector image in the parent NXdetector module.
> 
> The data_origin is 0-based.
> 
> The frame number dimension (np) is omitted. The order of indices is i, j or i, j, k, i.e. slow to fast.

To:

https://github.com/cctbx/cctbx_project/blob/master/dxtbx/format/nexus.py#L1638

`Assumes slices are stored in NeXus in fast to slow order.`

This affects the EuXFEL work I've been doing.  I've been writing NeXus files such that dxtbx can understand them, but here it seems we have the order backwards.

The source of this confusion is likely because of nexusformat/definitions#650.

I know DLS is writing NeXus files.  What are the data_origin/data_size fields being created there?  Are the panels square so this wouldn't have mattered?  If so we can fix this without affecting anyone.

**Comment by graeme-winter** [comment]
@phyy-nx not sure we use this for our NeXus files at Diamond, but I will investigate in the morning. Things like this can slip through, and I think it is appropriate if DIALS / dxtbx has it wrong that we fix, even if it involves changes elsewhere. 

I'll see if we use this for Eiger processing...

**Comment by phyy-nx** [comment]
👍

**Comment by graeme-winter** [comment]
Just added 

```
    all_slices = []
    for module in modules:
        data_origin = module.handle["data_origin"]
        print(data_origin)
        print(1/0)
```

and dials processing of an Eiger data set does not crash => we don't use this => fill your boots 🙂

**Comment by graeme-winter** [comment]
Looks like data_size is reversed in some of our files:

```
Grey-Area i04-eiger-small :) $ ~/svn/cctbx/base/bin/h5dump -d /entry/instrument/detector/module/data_size Therm_6_2_master.h5 
HDF5 "Therm_6_2_master.h5" {
DATASET "/entry/instrument/detector/module/data_size" {
   DATATYPE  H5T_STD_I32LE
   DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
   DATA {
   (0): 4148, 4362
   }
}
}
```

at least, from Diamond 🤔

**Comment by graeme-winter** [comment]
NXmx says

data_size: (required) NX_INT

Two or three values for the size of the module in pixels in each direction.

This is not helpful here. 

http://download.nexusformat.org/sphinx/classes/applications/NXmx.html?highlight=data_size

**Comment by phyy-nx** [comment]
Right, see nexusformat/definitions#650 which hopes to clarify this documentation.

**Comment by phyy-nx** [comment]
Ok, so nexus.py has two classes to read the data:

DataList: Used for single panel detectors, e.g. detectors without a NXdetector_group. Uses the shape of the data itself to reshape the data into flex.
MultiPanelDataList: Used if the detector has multiple modules organized by a NXdetector_group. 
 Uses data_origin and data_size to slice the raw data while building flex arrays for multiple panels.  

The fact that DataList doesn't use data_origin and data_size is a separate bug.  In fact, there's even a comment about this in the code:
https://github.com/cctbx/cctbx_project/blob/master/dxtbx/format/nexus.py#L1567 

So this will let us get away with swapping the order that MultiPanelDataList reads the data, since none of the Eiger NeXus files will be affected.
