### ISSUE TITLE
NeXus: 4 dimensional data arrays not supported

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/cctbx_project#306]
In NeXus, data arrays can be 3 or 4 dimensional but nexus.py only supports 3 dimensional arrays.

NXmx documentation:
http://download.nexusformat.org/sphinx/classes/applications/NXmx.html
```
data[np, i, j, k]: (required) NX_NUMBER

For a dimension-2 detector, the rank of the data array will be 3. For a dimension-3 detector, the rank of the data array will be 4. This allows for the introduction of the frame number as the first index.
```

Compare to:
https://github.com/cctbx/cctbx_project/blob/master/dxtbx/format/nexus.py#L548

`"data": {"minOccurs": 0, "checks": [check_dset(dims=3)]},`

This check_dset call fails for datasets with 4 dimensions.  Relevant because EuXFEL is constructing virtual datasets using 4 dimensional arrays.

**Comment by graeme-winter** [comment]
Are they using VDS, or a home brew version of the same? Because VDS should resolve this to make an apparent 3D data set from multiple blocks...

**Comment by graeme-winter** [comment]
As in HDF5 virtual data set in 1.10...

**Comment by phyy-nx** [comment]
Right, they are using VDS so they could make a 3D version instead of 4D.  I
didn't want to ask them to do this since 4D is in the specification and
it's not hard to support.

Full disclosure, I have a set of edits that implements 4D in dxtbx :)  I'll
make a branch soon with this.

**Comment by graeme-winter** [comment]
But is the data really a sequence of 3D frames, or a series of (n x 2D) frames? i.e. should we be modelling this as 3D data if it is not? Alternative use case: we are building a detector which can resolve the energy of events, so in principle one could record 3D images - x, y, e as a function of t. This would be 3D, and would collide with this definition. 

If you have the nframes x nmodules x 2D images in the data set making a VDS should be easy? That way the data seem more kin to other serial experiments.

**Comment by phyy-nx** [comment]
The data set is nframes x nmodules x 2D images and is already a VDS.  The
raw data is 16 separate hdf5 files, each representing a module, so it made
sense to use nframes x 16 x slow x fast as the dimensionality in the VDS.

FWIW this is the same convention as used in ImageCIF.
