### ISSUE TITLE
Need per-image mask support in NeXus

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/cctbx_project#308]
Assuming that per-image mask support is approved in NXmx (see  nexusformat/definitions#651), we need to add it in nexus.py to support the EuXFEL.  Currently, it is assumed the mask provided has dimensionality 1 less than the data array, meaning the mask applies to all the data.  However, the proposal is that if the mask has the same dimensionality as the data, then each image has a separate mask.

Example:
Data shape: nimages x slow x fast

Mask shape 1: slow x fast. This mask applies to the whole dataset.
Mask shape 2: nimages x slow x fast.  This array contains one mask per image.

**Comment by graeme-winter** [comment]
https://github.com/HDRMX/NXmx/wiki/Treatment-of-(Dynamic)-Shadows-in-Eiger-Data-Sets

Useful?

**Comment by phyy-nx** [comment]
Indeed!  I had meant to look at this more carefully.  Is this a proposal meant as an update to NeXus or to the NearlyNexus Eiger format?

**Comment by graeme-winter** [comment]
Full NeXus is proposal

**Comment by phyy-nx** [comment]
Ok thanks.  I've updated the NeXus issue I created to point to the HDRMX wiki page.
