### ISSUE TITLE
install with conda appears to fail due to unavailable download

### ISSUE THREAD

**Issue by mrp-xtals** [cctbx/cctbx_project#314]
CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/hdf5-1.10.4-nompi_h11e915b_1105.tar.bz2>

from https://conda.anaconda.org/conda-forge/linux-64/
the closest match is

hdf5-1.10.4-nompi_h3c11f04_1106.tar.bz2 3839809cfac5b3a880a4fde18e7b993a

can the script  be corrected to link to the available tarball?

**Comment by phyy-nx** [comment]
Hi, I updated the versions best I could.  Tested on linux.  I'll watch the builds tonight for mac/windows and see how it goes.  Thanks for point this out.

**Comment by nwmoriarty** [comment]
Which bootstrap.py did you change? The one in cctbx_project or buildbot repo?

**Comment by phyy-nx** [comment]
I didn't change bootstrap.py. I changed the manifest files.  So those are in cctbx_project.

**Comment by ndevenish** [comment]
Wouldn't there be value in putting this process into a CI job?

**Comment by phyy-nx** [comment]
Which process do you mean?  The conda build step?  We run 'base' on all our
buildbot builds nightly.  Now that we are on conda it runs much much faster
than it used to.  So I'm not sure a separate CI 'base only' step is needed.

Or do you mean a CI that monitors if those links are good?  That I could
get on board with.  Not knowing when conda-forge takes down a package for
some reason seems like a problem.

**Comment by ndevenish** [comment]
I mean - this list is just generated automatically from the dependency list, right? Just something to regenerate that list and update it if something has changed, rather than manually which it looks like you/Billy have been doing occasionally.

**Comment by phyy-nx** [comment]
Oh I getcha.  Ok, that's something to look into.  Thanks.
