### ISSUE TITLE
Cannot address ExperimentList with a negative number

### ISSUE THREAD

**Issue by dagewa** [cctbx/cctbx_project#32]
[This](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fdials%2Fdials%2Fblob%2Fmaster%2Falgorithms%2Findexing%2Findexer.py%23L835&sa=D&sntz=1&usg=AFQjCNEPEp7qSj1HR20-pGL97BJhpn2Xyw) used to be possible:

`del experiments[-1]`

After the changes to move ExperimentList to C++ it no longer works:

```
>>> from dxtbx.model import Experiment, ExperimentList
>>> el=ExperimentList()
>>> el.append(Experiment())
>>> el.append(Experiment())
>>> el[-1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: can't convert negative value to unsigned
```

I think we'd like to keep the Python list-like behaviour, so could we get `experiments[-1] ` working again please?

**Comment by jmp1985** [comment]
Should now work
