### ISSUE TITLE
mtz.object.delete_reflections() is hideously inefficient

### ISSUE THREAD

**Issue by rjgildea** [cctbx/cctbx_project#320]
mtz.object.delete_reflections() is hideously inefficient when deleting a large number of reflections. This can end up being a bottle neck in the xia2 rebatch function:

https://github.com/xia2/xia2/blob/70a87331b22cd0b2d378b6a0ed120f483ca52ece/Modules/Scaler/rebatch.py#L88

https://github.com/cctbx/cctbx_project/blob/666f100f60722b554cc7f8e440eb14bfe9a27f8f/iotbx/mtz/object.h#L575-L585

See comment above in the code for delete_reflections (which is called by delete_reflections for every reflection being deleted):
https://github.com/cctbx/cctbx_project/blob/666f100f60722b554cc7f8e440eb14bfe9a27f8f/iotbx/mtz/object.h#L568-L573

**Comment by ndevenish** [comment]
Calls https://github.com/dials/ccp4io/blob/af475d643cd50d6723a6665e42399e2e0bdb641a/libccp4/ccp4/cmtzlib.c#L2457-L2472 which in turn calls https://github.com/dials/ccp4io/blob/af475d643cd50d6723a6665e42399e2e0bdb641a/libccp4/ccp4/ccp4_array.c#L116-L124 - and all the time is spent in the `memmove`.

Can probably do the whole operation in one pass, but changes need to be done carefully - and I'm not actually sure where ccp4io is kept?

**Comment by Anthchirp** [comment]
there is none.
ccp4io is in the list of repositories that were un-repositoried because nobody changed anything in them.
We can un-un-repository it and point bootstrap to pick it up from github.

**Comment by Anthchirp** [comment]
-> https://github.com/cctbx/ccp4io

**Comment by Anthchirp** [comment]
looking at this in branch iotbx-320
