### ISSUE TITLE
Access to gitcdn blocked

### ISSUE THREAD

**Issue by frankvm04** [cctbx/cctbx_project#352]
Access to gitcdn.xyz is blocked at many institutions (including the 2 I have access to) — making it impossible to use bootstrap to build. While it is possible get a VPN account outside and use this when building, it seems easier to find alternate sources for Python and OpenSSH.

**Comment by Anthchirp** [comment]
I've recently put in the logic to support alternative download locations (https://github.com/cctbx/cctbx_project/commit/3b2f20ad9703b981120903fad34c65d43c1b1b86), but haven't enabled this on master yet. I've used this in out release branch and it seems to work well, so will copy it over shortly.

**Comment by frankvm04** [comment]
Excellent!
