### ISSUE TITLE
Fix deprecations in xfel

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/cctbx_project#385]
TODO (lifted from dials/dials#885, thanks @benjaminhwilliams for pointing it out)

- [ ] Replace dials.util.halraiser with dials.util.show_mail_on_error context manager;
- [ ] Replace dxtbx.model.experiment_list.ExperimentListDumper and dxtbx.serialize.dump with as_file method of experiment list
- [x] Replace dials.algorithms.indexing.index_reflections with dials.algorithms.indexing.assign_indices.AssignIndicesGlobal (not in xfel but could be in extant repositories)
- [ ] Fix DeprecationWarning: Setting verbosity for a Refiner is deprecated. See dials/dials#860

**Comment by benjaminhwilliams** [comment]
Hi @phyy-nx, I actually accidentally performed most of these conversions in `xfel` when I did a semi-automated conversion for dials/dials#885 (I did it on the whole codebase by accident).  I'll check there are no dodgy conversions and open a PR for you to look at.
