### ISSUE TITLE
dxtbx's read_uint32 does not

### ISSUE THREAD

**Issue by dagewa** [cctbx/cctbx_project#39]
Quite possible I'm just getting confused, but my expectation of the script below is that read_uint32 should read the value 4294967295 here, not -1.

```
import struct, binascii

# maximum value of unsigned int
uint_max = 4294967295
assert binascii.hexlify(struct.pack('<I', uint_max)) == 'ffffffff'

with open("onebyte.bin","wb") as f:
  f.write(struct.pack('<I', uint_max))

# external check:
# $ hexdump -C onebyte.bin 
# 00000000  ff ff ff ff                                       |....|
# 00000004

from boost.python import streambuf
from dxtbx import read_uint32

with open("onebyte.bin", "rb") as f:
  data = read_uint32(streambuf(f), 1)

print list(data)
# [-1]

```

**Comment by dagewa** [comment]
So, I suppose the problem is here, in `dxtbx/boost_python/ext.cpp`

`scitbx::af::shared<int> result`

the return type cannot represent all values of a uint32. Probably okay then...

**Comment by jmp1985** [comment]
Hi David,

I guess the use of flex.int as a return type for read_uint32 is probably a bit confusing. I would imagine that the original reason for doing this is because we generally handle int/double image data so it was easier to export as flex.int. Also, I would guess that the typical diffraction image doesn't record counts up to 4294967295 counts per pixel!

James

________________________________

**Comment by dagewa** [comment]
Yeah, I think if we can't return data as an unsigned int then I think we shouldn't have a function to read that type. If I try changing the return value to unsigned int it can build but my test script ends up with

`TypeError: No to_python (by-value) converter found for C++ type: scitbx::af::shared<unsigned int>`

**Comment by dagewa** [comment]
Possibly a better solution would be to keep that function, but add a check to it so that it fails if the returned array contains any negative values. What do you think?

**Comment by jmp1985** [comment]
Hi David,

I guess that no flex.unsigned_int type is exported. There is flex.size_t type, so if you change the return type to size_t that will work. However, on 64-bit systems this will be a 64bit unsigned integer though.

James

________________________________

**Comment by dagewa** [comment]
Not sure what's best. Some options

1. Export flex.unsigned_int type (most work)
2. Change return to flex.size_t, accept that this is using twice as much memory as required on 64 bit systems (annoying)
3. Change read_uint32 to fail whenever the return value would be negative
4. Remove read_uint32. No current formats actually use this. The only example in dxtbx is an optional type for the format I'm working on and I don't have any files with data stored in that type

I prefer 3 or 4 for practical reasons

**Comment by jmp1985** [comment]
Hi David,

I'm trying to remember where but I think I came across the an unsigned int dataset somewhere! I think do option 3.

James

________________________________
