### ISSUE TITLE
Fix missing anomalous=None in as_miller_array functions

### ISSUE THREAD

**Issue by phyy-nx** [cctbx/cctbx_project#395]
Several tests in phenix_regression are failing since #391 was merged.  These are the tests:

modules/phenix_regression/mmtbx/bulk_sol_and_scaling_fast/tst.py
modules/cctbx_project/cctbx/regression/tst_miller_statistics.py
modules/phenix_regression/iotbx/tst_french_wilson.py
modules/phenix_regression/mmtbx/tst_xmanip.csh
modules/phenix_regression/refinement/tst_089.py
modules/phenix_regression/iotbx/tst_reflection_file_reader.csh
modules/phenix_regression/misc/tst_hyss_etc.csh
modules/phenix_regression/refinement/autobuild/tst.py
modules/phenix_regression/gui/tst_hyss_gui.py
modules/phenix/phenix/regression/tst_xmanip.py

Fixing the tests generally entails adding anomalous=None to a few classes in iotbx implement the as_miller_arrays function.  This issue can be closed when that has been done.

FYI, to help catch these failures in the future:
1. phenix_regression and phenix_examples have been added to the cctbx_project Azure pipelines, so test modules/cctbx_project/cctbx/regression/tst_miller_statistics.py which expects phenix_examples now fails(before it was skipped) (see for example https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=756&view=logs).
2. The remaining tests in phenix_regression and phenix may be moved into iotbx after this week's phenix workshop.
3. Phenix itself will have an Azure pipeline set up at some point.  Its tests may be added as checks on cctbx branches like the cctbx_project pipeline checks that are present now, but it depends on how long the phenix builds take.  We're still figuring how many resources from Azure we can commit to each pipeline.

**Comment by phyy-nx** [comment]
@rjgildea can you look into this?  If you can't get to it, can we revert #391 until the whole API can be patched in one go?  We need the API working for current development work.  Thanks for your attention.

**Comment by rjgildea** [comment]
Sorry, I started looking at this the other day and then got distracted and forgot about it. I'll try to look at it again tomorrow.

**Comment by phyy-nx** [comment]
Thanks!

**Comment by phyy-nx** [comment]
Tests still failing:

- [ ]  modules/phenix_regression/misc/tst_hyss_etc.csh
- [ ]  modules/phenix_regression/iotbx/tst_iotbx_reflection_file.csh

**Comment by rjgildea** [comment]
phenix_regression/iotbx/tst_iotbx_reflection_file.csh should now be fixed by https://github.com/cctbx/cctbx_project/commit/b2783566840ae3392e09171bcb4141e46e6481e5.

As far as I can tell the error in phenix_regression/misc/tst_hyss_etc.csh is unrelated to any changes I made, and was indeed failing these changes were introduced. I have checked out commit 91f3f8b3cc271824c4460a031cd3be3027f6c321 of cctbx and I still see the following errors:

```
$ csh ../modules/phenix_regression/misc/tst_hyss_etc.csh
BEGIN OF INPUT (libtbx.assert_stdin_contains_strings)
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Reference model:
Number of scatterers: 12
At special positions: 0
Unit cell: (108.742, 61.679, 71.652, 90, 97.151, 90)
Space group: C 1 2 1 (No. 5)

Number of scatterers: 12
At special positions: 0
Unit cell: (108.742, 61.679, 71.652, 90, 97.151, 90)
Space group: C 1 2 1 (No. 5)

Match summary:
  Operator:
       rotation: {{-1, 0, 0}, {0, -1, 0}, {0, 0, -1}}
    translation: {1.50463*^-36, 0.198902, 0}
  rms coordinate differences: 0.41
  Pairs: 10
    pdb="PEAK PEAK    1 " segid="PEAK" site002 0.140
    pdb="PEAK PEAK    3 " segid="PEAK" site005 0.466
    pdb="PEAK PEAK    4 " segid="PEAK" site010 0.368
    pdb="PEAK PEAK    5 " segid="PEAK" site003 0.139
    pdb="PEAK PEAK    6 " segid="PEAK" site004 0.279
    pdb="PEAK PEAK    7 " segid="PEAK" site001 0.431
    pdb="PEAK PEAK    8 " segid="PEAK" site008 0.289
    pdb="PEAK PEAK    9 " segid="PEAK" site009 0.921
    pdb="PEAK PEAK   10 " segid="PEAK" site007 0.147
    pdb="PEAK PEAK   11 " segid="PEAK" site006 0.325
  Singles model 1: 2 
    pdb="PEAK PEAK    2 " segid="PEAK"   pdb="PEAK PEAK   12 " segid="PEAK" 
  Singles model 2: 2 
    site011   site012 


match_list: [10/12]
matches: frequency
   10:   1 = 100.0%, 100.0%

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
END OF INPUT (libtbx.assert_stdin_contains_strings)
Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/cctbx_project/libtbx/command_line/assert_stdin_contains_strings.py", line 24, in <module>
    run(sys.argv[1:])
  File "/Users/rjgildea/software/cctbx/build/../modules/cctbx_project/libtbx/command_line/assert_stdin_contains_strings.py", line 21, in run
    raise AssertionError("String %s in input: %s" % (s, arg))
AssertionError: String not in input: match_list: [12/12]
BEGIN OF INPUT (libtbx.assert_stdin_contains_strings)
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
Miller array info: gere_MAD_anom_diffs.hkl:Fobs,SigFobs
Observation type: xray.amplitude
Type of data: double, size=7820
Type of sigmas: double, size=7820
Number of Miller indices: 7820
Anomalous flag: False
Unit cell: (108.742, 61.679, 71.652, 90, 97.15, 90)
Space group: C 1 2 1 (No. 5)

Number of scatterers: 12
At special positions: 0
Unit cell: (108.742, 61.679, 71.652, 90, 97.151, 90)
Space group: C 1 2 1 (No. 5)

gere_MAD_hyss_consensus_model.pickle: correlation after site refinement: 0.333
gere_MAD_hyss_consensus_model.pickle: correlation after occupancy refinement: 0.335
gere_MAD_hyss_consensus_model.pickle: correlation after site+occupancy refinement: 0.335

u+s,u,s: 1.23 1.13 0.10
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
END OF INPUT (libtbx.assert_stdin_contains_strings)
Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/build/../modules/cctbx_project/libtbx/command_line/assert_stdin_contains_strings.py", line 24, in <module>
    run(sys.argv[1:])
  File "/Users/rjgildea/software/cctbx/build/../modules/cctbx_project/libtbx/command_line/assert_stdin_contains_strings.py", line 21, in run
    raise AssertionError("String %s in input: %s" % (s, arg))
AssertionError: String not in input: gere_MAD_hyss_consensus_model.pickle: correlation after site+occupancy refinement: 0.347
DONE: ../modules/phenix_regression/misc/tst_hyss_etc.csh
```

**Comment by phyy-nx** [comment]
@bkpoon reports all these tests are passing now.  No need to revert any of the changes from #391.  

Closing. Thanks to all who worked on this
