### ISSUE TITLE
DIALS builder prevents having phenix simultaneously configured

### ISSUE THREAD

**Issue by rjgildea** [cctbx/cctbx_project#399]
It appears to be impossible to have phenix configured within a DIALS development environment, as a result of:
https://github.com/cctbx/cctbx_project/blob/2798d979a2d9b2e26763f061a665ef62efce7ca1/libtbx/env_config.py#L1310-L1311

This prevents easily running cctbx tests that require phenix/phenix_regression (see e.g. https://github.com/cctbx/cctbx_project/issues/395).

**Comment by phyy-nx** [comment]
IIRC, this is by design since in the dials builder, the phenix modules are not available or configured:

https://github.com/cctbx/cctbx_project/blob/master/libtbx/auto_build/bootstrap.py#L2023

 You can use the phenix builder with bootstrap (requires --cciuser) or you can manually configure dials and phenix_regression using libtbx.configure.

**Comment by rjgildea** [comment]
But despite attempting to configure the phenix modules, the phenix.* dispatchers are not created because of the above lines.

**Comment by phyy-nx** [comment]
Right, sorry, here's what I meant.

1. Until these tests are moved out of phenix_regression into cctbx_project, the standard way of running the tests is `python bootstrap.py --builder=phenix`, then running checking out phenix_regression into modules and running `libtbx.configure phenix_regression`.
2. For an existing dials build:

Using conda:
```
conda activate /dev/shm/aaron/dialsBuild/conda_base
mkdir build; cd build
python ../modules/cctbx_project/libtbx/configure.py dials phenix_regression
```
Using a base folder from install_base_packages should be like this:
```
mkdir build; cd build
../base/bin/python ../modules/cctbx_project/libtbx/configure.py dials phenix_regression
```
I see all the phenix dispatchers when I do the conda version.  Here's, bootstrap.py isn't invoked so skip_phenix_dispatchers isn't set.
