### ISSUE TITLE
iotbx.xds.xparm reads too much

### ISSUE THREAD

**Issue by dagewa** [cctbx/cctbx_project#40]
This line

`      lines = file_handle.readlines()`

in [xparm.py](https://github.com/cctbx/cctbx_project/blob/master/iotbx/xds/xparm.py#L40) causes problems for e.g. dials.import, because it reads the entire file into memory. This happens when `FormatXDS` is trying to `understand` an image file - bad news in the case I've just looked at, when that file is a 7.5GB multi-image file!

**Comment by dagewa** [comment]
Out of time to fix today, but suggested fix, read only some number of bytes that is the maximum expected for an XPARM file (whch is how many?)

**Comment by ndevenish** [comment]
I didn't catch the entire context in the conversation earlier, I thought it was just using `readline`. I believe the iterator form `for line in file` only reads in chunks. So perhaps change:

      lines = file_handle.readlines()
      assert len(lines)
      for count, line in enumerate(lines):

to:

    for count, line in enumerate(file):

**Comment by ndevenish** [comment]
It might also be worth, as another option, using the `readlines([sizehint])` [form](https://docs.python.org/2/library/stdtypes.html#file.readlines) which in principle limits the chunk read to some upper bound in bytes.

**Comment by dagewa** [comment]
It seems there is no upper limit on the size of a [(G)XPARM.XDS](http://xds.mpimf-heidelberg.mpg.de/html_doc/xds_files.html) file because there could be an arbitrary number of detector segments defined at the end. However, the `for count, line in enumerate(file_handle):` form can readily be applied here.

Just running the tests then will commit the fix. Also, will poke around for other instances of `readlines()` that might be called by `dxtbx`. They are probably not what is wanted!
