### ISSUE TITLE
bootstrap and Google Drive links

### ISSUE THREAD

**Issue by bkpoon** [cctbx/cctbx_project#405]
@Anthchirp Is there a way to reproduce the permissions error you describe in 54344b84c0b4fd00c5ca8438b98a501eca503fae?

Since power has been restored, the Google Drive links will be changed to be secondary sources.

**Comment by Anthchirp** [comment]
Yes, a standard `bootstrap hot update base build --builder=dials` on linux was enough to trigger this.

I would also generally recommend against using Google Drive links, as it is intransparent what they refer to.

**Comment by bkpoon** [comment]
I've tested `python bootstrap.py hot update --builder=dials` with the [bootstrap.py](https://raw.githubusercontent.com/cctbx/cctbx_project/384724d3f7ed821f967884cffab0b10d0d560781/libtbx/auto_build/bootstrap.py) from 384724d3f7ed821f967884cffab0b10d0d560781 on multiple, independent, linux computing environments (LBL, NERSC, SLAC/LCLS, SwissFEL) with multiple users and I'm not able to get the permissions error.

I can reproduce the permissions error if I change the permissions of an existing `ccp4io` directory so that I cannot write to the directory. So starting from an existing installation with the `modules` directory,

1) `chmod -R u-w ./modules/ccp4io/*`
2) `python bootstrap.py hot update --builder=dials`

And the output is,
```
Performing actions: hot update
===== Downloading https://drive.google.com/uc?id=1YD_KDXrfhJ5ryT97j4yxmbAPoecGLjg0&export=download:  0.5 MB
    [0%.........20%.........40%.........60%.........80%.........100%]
===== Running in modules: extracting files from annlib.gz
===== Downloading https://drive.google.com/uc?id=1hPd5cMbVcsN4j0P5qaPUV71XS_aifw-J&export=download:  0.9 MB
    [0%.........20%.........40%.........60%.........80%.........100%]
===== Running in modules: extracting files from scons.gz
===== Downloading https://drive.google.com/uc?id=1EF6AqowSrVnse7pRtRmIsvhS6Q0dsSLT&export=download:  2775 kB
===== Running in modules: extracting files from ccp4io.gz
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "bootstrap.py", line 99, in tar_extract
    + traceback.format_exc())
Exception: Extracting tar archive resulted in error: [Errno 13]
Permission denied: 'ccp4io/lgpl-3.0.txt'
Traceback (most recent call last):
  File "bootstrap.py", line 83, in tar_extract
    tar.extractall(path=workdir)
  File "/usr/lib64/python2.6/tarfile.py", line 2036, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib64/python2.6/tarfile.py", line 2073, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib64/python2.6/tarfile.py", line 2151, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib64/python2.6/tarfile.py", line 2190, in makefile
    target = bltn_open(targetpath, "wb")
IOError: [Errno 13] Permission denied: 'ccp4io/lgpl-3.0.txt'

Process failed with return code 1
```
Is this error in your Jenkins build?

The Google Drive links are temporary placeholders.

**Comment by Anthchirp** [comment]
this is no longer relevant
