### ISSUE TITLE
iotbx/shelx/tst_hklf.py broken

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#406]
caused by 8aa58ebb4ee41c5c1b2f00f7e7897e7b5fde59c9

The commit explicitly removes the `scale_range` keyword from the `export_as_shelx_hklf` function in `cctbx/miller/__init__.py`.

I have no idea why and the commit message doesn't tell me either, so will leave it for someone else to figure out.

**Comment by terwill** [comment]
Hi Marcus,
Thank you, we do know that this test fails and we're working on it.
Thanks!
-Tom
