### ISSUE TITLE
dxtbx: FormatEigerStream reads entire file

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#41]
Following on from #40 this here also isn't very nice
```python
header = json.load(open(image_file))
```
https://github.com/cctbx/cctbx_project/blob/master/dxtbx/format/FormatEigerStream.py#L20

**Comment by dagewa** [comment]
Is first non-whitespace byte always '`{`'? Might be a shortcut there for refusing to `understand` further. Getting more complicated, [stackoverflow](https://stackoverflow.com/questions/10382253/reading-rather-large-json-files-in-python/10382359#10382359) suggests ijson. That might be worth it if these JSON files are big anyway. This code looks to be for images packed into JSON. I imagine these could be on the portly side.

**Comment by jmp1985** [comment]
IJSON looks interesting; however, I would imagine that this format class is currently not used anywhere so maybe best to disable for the moment.
________________________________

**Comment by Anthchirp** [comment]
in which case this can then probably be closed
