### ISSUE TITLE
missing scipy dependency

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#434]
Since approximately https://github.com/cctbx/cctbx_project/commit/0bec3ec293aeb66efc8e67a37c0ebe8a6ea88175 iotbx and cctbx depend on scipy. However scipy is not installed as a dependency in install_base_packages.py (unless one uses the dials installer, https://github.com/cctbx/cctbx_project/blob/master/libtbx/auto_build/install_base_packages.py#L279-L282)

**Comment by pafonine** [comment]
Are we absolutely sure we need to bring in the entire package (scipy) 
just to do interpolation? I doubt..


/Users/pafonine/phenix/modules/cctbx_project/cctbx % libtbx.find_files 
-g scipy
./xray/structure_factors/from_scatterers_direct_parallel.py:     1. 
numpy package (http://numpy.scipy.org) version 1.5.1 OK
/Users/pafonine/phenix/modules/cctbx_project/cctbx % cd ../mmtbx/
/Users/pafonine/phenix/modules/cctbx_project/mmtbx % libtbx.find_files 
-g scipy
./validation/rama_z.py: from scipy import interpolate
./validation/grid2d.py: from scipy import interpolate

**Comment by olegsobolev** [comment]
I'll work to get rid of it soon.

**Comment by olegsobolev** [comment]
@Anthchirp 
I removed the dependency: 415fdc8aa8789a0472634788a842ea93ed88df01

**Comment by Anthchirp** [comment]
This has been fixed
