### ISSUE TITLE
how to download chem_data

### ISSUE THREAD

**Issue by danpf** [cctbx/cctbx_project#448]
Hello,
How do i download the 'chem_data' folder to use the tools from the molprobity validation suite?
Thanks!
edit (sorry  follow https://github.com/rlabduke/MolProbity/blob/master/install_via_bootstrap.sh)

**Comment by danpf** [comment]
Ok I think I have everything working except: I can't find `chem_data/rama_z/top8000_rama_z_dict.pkl`

how can i download/build that?

**Comment by olegsobolev** [comment]
I'm not sure how it should be made available to public, but here it is:
[top8000_rama_z_dict.pkl.zip](https://github.com/cctbx/cctbx_project/files/4331293/top8000_rama_z_dict.pkl.zip)

**Comment by danpf** [comment]
appreciate it @olegsobolev !
