### ISSUE TITLE
CCTBX releases

### ISSUE THREAD

**Issue by bkpoon** [cctbx/cctbx_project#451]
With `conda` packages available for testing on linux, macOS, and Windows for Python 2.7, 3.6, 3.7, and 3.8 (except for Windows), with

`conda create -n test -c cctbx-dev cctbx python=<python version>`

(`conda create -n test -c cctbx-dev cctbx python=3.7` will create an environment named `test` that will have `cctbx` and Python 3.7) or 

`conda install -c cctbx-dev cctbx`

(this will install `cctbx` into the currently active environment), the next step is to have an official release. Then the recipe at `conda-forge` (https://github.com/conda-forge/staged-recipes/pull/10021) can progress and we can have an official `conda` package on `conda-forge`. So some items open for discussion are,

1) **Versioning** - I think we are a little late for 1.0.0 (semantic versioning, https://semver.org), and so I have been using a simple YYYY.MM format (calendar versioning, https://calver.org) just to make it easy to get an idea of when the package was built.
2) **Release schedule** - Since it'll be straightforward to do releases with GitHub and Azure Pipelines, we can do monthly (or every other month) builds (source and binary installers) and the `conda-forge` package can be automatically built with their infrastructure.
3) Any other topics for releases?

Then there will be a discussion among the higher ups and PIs.

Note: The `cctbx` package requires dependencies from the `conda-forge` channel. You can add the channel by modifying your ~/.condarc file to have something that looks like
```
channels:
  - conda-forge
  - defaults
```
Additional discussion about the `conda` package is also on the cctbxbb and phenixbb bulletin boards (http://phenix-online.org/pipermail/cctbxbb/2020-March/002202.html,  http://phenix-online.org/pipermail/phenixbb/2020-March/024564.html)

**Comment by Anthchirp** [comment]
Great work!
Is there a plan for release support or will releases just be snapshots of whatever master happens to be on the day?

**Comment by graeme-winter** [comment]
Hi @bkpoon apropos Python 2.7 binaries - looks like conda-forge have just officially dropped support - https://github.com/conda-forge/cfep/pull/26 - beyond that conda support for cctbx packages I am sure will be welcome amongst the end user community - "why can't I easily add cctbx to my Python" was a common refrain...

**Comment by bkpoon** [comment]
@Anthchirp I'm not seeing much interest in back porting fixes to previous releases. So monthly or bimonthly (every 2 months) releases should let us push out bug fixes or new features relatively quickly. There would probably be a window of a few days in picking which commit to tag as a release so that it doesn't have some massive bug. This approach would also avoid having to create release branches that would clutter up the repository, especially if we do monthly releases.

Phenix will continue making a branch of `cctbx_project` in our fork for Phenix releases so that we can be on a separate schedule. Also, if we really needed to, we could back port a fix for a particular Phenix release, but this has been very rare.

@graeme-winter Yes, but the ability to build a package for Python 2.7 still exists (https://conda-forge.org/docs/user/announcements.html#id1). This will help users migrate and test their existing scripts or package.

I'll also set up nightly builds of the `conda` package for testing `cctbx_project` against the latest dependencies that would be pulled from `conda-forge`.

**Comment by Anthchirp** [comment]
Following up on this,
We have maintained release branches for `cctbx_project` for DIALS [for the last 4 years](https://github.com/dials/cctbx/branches/all), so while you may not be _seeing_ much interest, it definitely exists :smiley: 

I don't see the point of not having release branches in the repository if you need to tag them anyway - a tag and a branch have the same cost in terms of git. However it is your repository and your decision.

If you do not want to allow release maintenance in the repository then I see a huge issue in that we would not be able to use the cctbx_project conda forge packages for DIALS releases. I therefore suggest that the best alternative way forward would be for us to pick certain cctbx releases and maintain them for however long we need _on conda-forge_ using patch files. Would you be happy for us to do this?

**Comment by bkpoon** [comment]
We can have release branches and point releases if that's useful for all users. Phenix can use these point releases too. There should a similar window, let's say a week (7 days), for other developers to put any fixes they want into the point release. So the procedure could be

1) Create a pull request for a release (or point release) at a certain commit and branch at that point with a release branch (e.g. release/<version>)
2) One week of input from developers for which commits should be included in the release.
3) Create the source installer, update the conda-forge package, build binary installers with the conda packages.

Would that work for DIALS?

**Comment by Anthchirp** [comment]
That sounds great and if it's useful for everyone then that's even better :+1:

(On the release branch name I would suggest adding a non-`[0-9a-f]` prefix, for example `v2020.04` as we recently noticed that pure numeric names can be confused for commit IDs in git.)

**Comment by graeme-winter** [comment]
@bkpoon did this come to pass?

**Comment by bkpoon** [comment]
Actually, we can start release branches if you need them for DIALS releases.

The official `conda` package in `conda-forge` is still a work in progress as we get `mmtbx` working in Python 3 and I'm sorting out the configuration of other modules that would use the `cctbx` package. There is a Phenix release in September, which we will want to have a beta version using `conda` packages for testing.

I can also start doing nightly `conda` package builds for the `cctbx-dev` channel in August. So how about a release branch in August? Or do you want something sooner?

**Comment by Anthchirp** [comment]
Seeing that we now have releases I assume this can be closed
