### ISSUE TITLE
ADSC JCSG images have incorrectly flagged bad pixels (all pixels with value -2)

### ISSUE THREAD

**Issue by rjgildea** [cctbx/cctbx_project#48]
This later results in almost all reflections failing in integration due to failures in background modelling.

```
$ dials.import /dls/metrix/metrix/anomalous_data/1VKN/b5_6_001.img 
DIALS 1.dev.1524-gc2f4a1e
The following parameters have been modified:

input {
  datablock = <image files>
}

--------------------------------------------------------------------------------
  format: <class 'dxtbx.format.FormatSMVADSCSN445.FormatSMVADSCSN445'>
  num images: 1
  num sweeps: 1
  num stills: 0
--------------------------------------------------------------------------------
Writing datablocks to datablock.json

$ dials.export_bitmaps show_mask=True datablock.json 
The following parameters have been modified:

show_mask = True
input {
  datablock = datablock.json
}

Exporting ./image0001.png
```
![image0001](https://user-images.githubusercontent.com/2810624/27643858-25e0a41e-5c1a-11e7-9c15-06211ad11874.png)

**Comment by graeme-winter** [comment]
Occurs to me gain for this detector != 1

**Comment by dagewa** [comment]
Possibly should be about 2.4 ADU per 12 keV X-ray (that is the case for
Q315s anyway)

-- David

**Comment by rjgildea** [comment]
I think the pixels with values -2 aren't actually masked out, it is just an artefact of the image viewer.

**Comment by rjgildea** [comment]
@graeme-winter is this treatment of image pedestal in the format class correct?
https://github.com/cctbx/cctbx_project/blob/master/dxtbx/format/FormatSMVADSCSN445.py#L89

**Comment by dagewa** [comment]
Exactly this in SMV Formats was mentioned today. Such things should be occurring in the get_corrected_data function, not get_raw_data. But subtracting the pedestal of 40 ADUs is indeed necessary to get e.g. proper reflection centroids and sigIs

**Comment by rjgildea** [comment]
But is image_pedestal = 40 actually correct here? After subtracting the image_pedestal, 2636798/4194304 (i.e. over half) pixels have negative values for the first image.

**Comment by dagewa** [comment]
I always thought pedestal = 40 was true for all ADSC CCD detectors, but your experience does suggest otherwise.

**Comment by phyy-nx** [comment]
What is the distribution of the pixels?  A good pedestal correction would
put it centered on zero with a positive tail, yes?

**Comment by rjgildea** [comment]
According to the format class, these images are from ALS 8.2.1:

```
# An implementation of the SMV image reader for ADSC images. Inherits from
# FormatSMVADSC, customised for example on ALS beamline 8.2.1 from back in the
# day which had it's own way of recording beam centre.
```

**Comment by dagewa** [comment]
@phyy-nx Only if no significant background scatter. You'd really want the median of a dark image.

**Comment by phyy-nx** [comment]
Gotcha

**Comment by dagewa** [comment]
Is there anything like `PED_FRACT_0` in the header...?

**Comment by rjgildea** [comment]
It looks like @graeme-winter added this image_pedestal subtraction ~3 years ago:
https://github.com/cctbx/cctbx_project/commit/a90743f61378f06c5101c1126d510800e2a151eb

**Comment by rjgildea** [comment]
```
$ strings /dls/metrix/metrix/anomalous_data/1VKN/b5_6_001.img
HEADER_BYTES=  512;
DIM=2;
TYPE=unsigned_short;
BYTE_ORDER=little_endian;
BIN=none;
ADC=slow;
DETECTOR_SN=445;
BEAM_CENTER_X=105.10;
BEAM_CENTER_Y=104.50;
DENZO_XBEAM=105.50;
DENZO_YBEAM=105.10;
TIME=1.0;
DATE=Sun Sep 21 10:49:40 2003;
TWOTHETA=-0.001;
DISTANCE=350.0;
OSC_RANGE=1.000;
PHI=16.000;
OSC_START=16.000;
AXIS=phi;
PIXEL_SIZE=0.102400;
WAVELENGTH=1.0000;
UNIF_PED=1500;
SIZE1=1024;
SIZE2=1024;
CCD_IMAGE_SATURATION=65535;
SIZE1=2048;
SIZE2=2048;
CCD_IMAGE_SATURATION=65535;
```

**Comment by dagewa** [comment]
Nope, oh well. Seems the pedestal is set in software, and although is usually 40, it need not be. Sometimes `IMAGE_PEDESTAL=` is in the header, but here there are no clues

**Comment by dagewa** [comment]
I think possibly in this case the pedestal is correct but these images had a bad dark correction applied

**Comment by rjgildea** [comment]
Strangely there are two sweeps in this dataset, the first (b5_1) looks fine:
```
$ dials.export_bitmaps /dls/metrix/metrix/anomalous_data/1VKN/b5_1_001.img prefix=b5_1_
Exporting ./b5_1_0001.png
```
![b5_1_0001](https://user-images.githubusercontent.com/2810624/27647621-d73013cc-5c23-11e7-9867-cad4aa71a03a.png)

However the second does not:
```
$ dials.export_bitmaps /dls/metrix/metrix/anomalous_data/1VKN/b5_6_001.img prefix=b5_6_
Exporting ./b5_6_0001.png
```
![b5_6_0001](https://user-images.githubusercontent.com/2810624/27647806-658bbb3a-5c24-11e7-8cc4-287842beae3e.png)

**Comment by graeme-winter** [comment]
Looks like these may not be the final images for deposition?

https://proteindiffraction.org/project/TM1782_1vkn/

**Comment by graeme-winter** [comment]
OK, for CCD we should be able to verify that the pedestal we are subtracting is sensible, as the distribution of pixels less than (pedestal+background) should be a half-Gaussian - could we not test for this somehow?

**Comment by graeme-winter** [comment]
Dispersion map distinctly funky:

<img width="516" alt="screen shot 2017-06-29 at 07 26 49" src="https://user-images.githubusercontent.com/1241716/27674166-60fe1a22-5c9c-11e7-8e7c-5d5b633e166e.png">

**Comment by graeme-winter** [comment]
Yes, overriding the pedestal to 0 makes the image look right... Could be an artefact of a dodgy collection run?

**Comment by graeme-winter** [comment]
![histogram](https://user-images.githubusercontent.com/1241716/27674908-aebbfb3c-5c9f-11e7-8e3d-0d200892f230.png)

peak (histogram) should be > pedestal

**Comment by graeme-winter** [comment]
Hitting ISPyB now for prehistoric Diamond ADSC images which are blank, am sure I recorded some of those $backintheday

**Comment by graeme-winter** [comment]
./ispyb_dc_info 'select imageDirectory from DataCollection where imagePrefix like "%blank%" and imageSuffix like "%img%";'

**Comment by graeme-winter** [comment]
In other news; some ADSC formats *do not* subtract pedestal

**Comment by graeme-winter** [comment]
commit incoming on this; running tests now

**Comment by rjgildea** [comment]
Closing this issue as the problem appears to be with the dataset itself rather than incorrect pedestal subtraction.
