### ISSUE TITLE
CI checks for PRs aren't running all tests

### ISSUE THREAD

**Issue by benjaminhwilliams** [cctbx/cctbx_project#482]
I recently merged a PR to fix some apparently erroneous logic in calculating merging statistics (https://github.com/cctbx/cctbx_project/pull/477).  I waited about two weeks for comments and before I merged, I checked that the 97 CI checks for PRs all passed (https://github.com/cctbx/cctbx_project/runs/679161858).  Since many of these checks included names like 'build and test', I took them to mean that tests were run.

After merging, I see that a regression test is failing.  It seems this test relies on some data stored in something called `phenix_regression`.  Also, I can't work out how to run tests properly in CCTBX.  It seems to use some sort of non-standard in-house testing framework that I don't understand.

Might I suggest that PR CI checks run all regression tests, to avoid this happening again?  As a volunteer contributor, I would also suggest that the developer guidance in the wiki contains a lot of "don't"s and not a lot of "do"s.  This is a little opaque to outsiders, especially if the data necessary to run the tests aren't publicly available, as in this case.

**Comment by phyy-nx** [comment]
Regarding #477, all the iotbx tests ran in Azure on #477 and they all passed before it was merged, as you say.  Here's the logs for the PR itself:
https://github.com/cctbx/cctbx_project/pull/477/checks
Click on one of the CI jobs, click on "View more details on Azure Pipelines", then find the 'Test' step, and you'll see the full test log.  Here's the direct link to the raw results:
https://dev.azure.com/cctbx/3d754415-9516-43fb-8e21-e1fae873ee5e/_apis/build/builds/5569/logs/159.  You'll see that tst_merging_statistics.py passed.

If an Azure test fails, you can use e.g. https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=5067&view=ms.vss-test-web.build-test-results-tab to get information about the test and any error messages more easily than looking through the log.

It does look like Jenkins didn't run on #477.  Jenkins is running on master, and is reporting this test is failing.  It is passing on all the Azure CI builds.  I don't know why it's failing on Jenkins, but it's worth figuring out. Will #483 make it moot or do you think tst_merging_statistics.py will still be failing on Jenkins after #483 is merged?  If phenix_regression is needed for Jenkins builds, note that @bkpoon is in the process of getting into a public repo.

For docs, I agree documenting libtbx.run_tests_parallel would be good.  I think the docs could go on the wiki or on https://cctbx.github.io/.  For completeness, this is what Azure does:

https://github.com/cctbx/cctbx_project/blob/696096ec792b7ae289fabe9e50d87336f09339a6/.azure-pipelines/unix-conda-build.yml#L114-L118

@bkpoon could we make that set of modules be the default to help contributors not need that full command?  Then the command would be:

```
libtbx.run_tests_parallel nproc=4
```

Then, as you expand the set of tests the Azure builds are running (to include for example mmtbx), you could add to the list of default packages to test and contributors wouldn't need to update their commands?

**Comment by bkpoon** [comment]
Oh, I was not configuring `phenix_regression` and `phenix_examples` so that particular test was not finding the directory. I'm testing a fix in the `test2` branch. Thanks!

**Comment by benjaminhwilliams** [comment]
Hi @phyy-nx,

> Will #483 make it moot or do you think tst_merging_statistics.py will still be failing on Jenkins after #483 is merged?

Yes #483 fixes the test failure.  If you'd be happy to review that, I can squash-merge it as soon as you're satisfied.

Hi @bkpoon, many thanks!  That sounds grand.  Good to hear that it was the intention to run the regression tests on PRs all along.  Glad I could bring this to your attention.

Thanks both very much for your help.

**Comment by Anthchirp** [comment]
Just a few minor points:

> If an Azure test fails, you can use e.g. https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=5067&view=ms.vss-test-web.build-test-results-tab to get information about the test and any error messages more easily than looking through the log.

This page is not publicly accessible.

> It does look like Jenkins didn't run on #477.

We don't run Jenkins on pull requests.

> If phenix_regression is needed for Jenkins builds,...

We only use phenix_regression for tests with the Python 2 build (any only until mid-July, https://github.com/dials/dials/issues/1175), we don't run it on Python 3 builds as we are moving away from distributing extra packages to build nodes. But as it looks it will become part of the Azure pipeline so there is really no need for us to run it anymore anyway.

**Comment by bkpoon** [comment]
@benjaminhwilliams I committed the change and your test is now properly failing. Can you update your branch in #483 so that the tests run again?

@Anthchirp It's odd that the page is not publicly available since the test logs are available. But it looks like someone else thought so as well at about the same time as your bug report to Microsoft (https://developercommunity.visualstudio.com/content/problem/1051998/anonymous-users-cant-access-public-project-pipelin.html).

**Comment by benjaminhwilliams** [comment]
Hi @bkpoon, I don't think it's necessary to push a fresh commit to re-trigger the Azure jobs.  There's a _re-run_ button at https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=5577 for the _build & test_ stage:
![image](https://user-images.githubusercontent.com/11389015/83394564-b86f4580-a3f0-11ea-92a0-5e90de75b362.png)

I don't have sufficient privileges to use that though, I think it would need to be triggered by someone in the CCTBX developers group, so I'll push an empty commit to get things to run again.

**Comment by benjaminhwilliams** [comment]
Oh, I see I'm behind the times and the #483 had already been merged.  :+1:

**Comment by bkpoon** [comment]
@benjaminhwilliams So it looks like the pipeline runs on the final merged code for pull requests (https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers), so the latest run after @phyy-nx commit would have actually run the test.

Also, it seems like the pipeline can be triggered by a comment in the pull request (https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers). And it seems to work with #486. Can you try triggering a run?

**Comment by benjaminhwilliams** [comment]
Sure thing, I'll try, though I suspect I'll see the same permission error.  I'll wait until yours has run, but that will mean I probably can't run it until start of play tomorrow, BST (approx 1am PDT).

**Comment by bkpoon** [comment]
Great! @dcliebschner just triggered the `Checks` pipeline and she does not have an Azure account, so hopefully it should work for you.

**Comment by benjaminhwilliams** [comment]
@bkpoon, it works!  Nice find.  In fact I also find I can now re-run checks via the GitHub Azure interface, which was previously giving a permissions error.  So perhaps the previous problem was just a transient blip.

I guess this issue can now be closed.  Certainly the problem I originally reported seems to have been fixed.  Thanks.
