### ISSUE TITLE
new fft_stability test fails on MacOS

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#492]
Test introduced in ac61ec7b9ee36c25b54e290914e742e34bf1923e fails on Python 2 and Python 3 on Jenkins/MacOS:
`cctbx.regression.tst_fcalc_fft_stability` (from libtbx.run_tests_parallel):
```
approx_equal failed:
   (-25.66165404922424, 1558.6907630995277, -6.1809323091842496e-15)
   (-25.5, 1531.7, 0.0)
approx_equal failed:
   1320.85161091
   1411.8
approx_equal failed:
   806.180366557
   1026.0
Traceback (most recent call last):
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/cctbx/regression/tst_fcalc_fft_stability.py", line 51, in <module>
    exercise1()
  File "/Users/dlshudson/jenkins_slave/workspace/cctbx_test_mac/build_dials/modules/cctbx_project/cctbx/regression/tst_fcalc_fft_stability.py", line 44, in exercise1
    if not approx_equal(rmup[coord], value, 1):
IndexError: Index out of range.
```

**Comment by Anthchirp** [comment]
sorry, meant to tag @olegsobolev

**Comment by olegsobolev** [comment]
@bkpoon will mark it as unstable until we figure out what's going on (various platforms produce different results).

**Comment by Anthchirp** [comment]
just as a side note: It would help for future reference if you could tag commits related to an issue with the issue number, so that one can be found from the other :smile:

**Comment by Anthchirp** [comment]
seems to have been fixed.
