### ISSUE TITLE
Got an error when calling MolProbity validation

### ISSUE THREAD

**Issue by massyasha** [cctbx/cctbx_project#509]
==============================` Collecting inputs ==============================

Symmetry information was not found, putting molecule in P1 box.

                   ----------Processing PDB file(s)----------                  

(<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'split'",), <traceback object at 0x7fe9b85bf320>)
Traceback (most recent call last):
  File "/Users/massimo/Repositories/PhaserVoyager/src/Voyager/voyager_strategy.py", line 1078, in run_action
    output = action.run()
  File "/Users/massimo/Repositories/PhaserVoyager/src/Voyager/Actions/Sculptor.py", line 163, in run
    output = self.sculptor(self.argsparse)
  File "/Users/massimo/Repositories/PhaserVoyager/src/Voyager/Actions/Sculptor.py", line 285, in sculptor
    final_sculpted, nosculpted, modifications, retname = self.sculpting(dictio, basedir, sculptor_mode, alisource, alipath, pdblist, alignments_from_hhpred, seqstr, ele, evaluate=extracted_entries, errorlist=errorlist)
  File "/Users/massimo/Repositories/PhaserVoyager/src/Voyager/Actions/Sculptor.py", line 349, in sculpting
    modifications, alipath = self.phaser_sculptor(dictio_arguments, alisource, alipath, directory, pdb_list, sculptor_mode, alignments_from_hhpred, sequence, seqstr, branch, save_original=False)
  File "/Users/massimo/Repositories/PhaserVoyager/src/Voyager/Actions/Sculptor.py", line 1083, in phaser_sculptor
    result = self.mmtbx_commandline_molprobity.molprobity.run([pdbf])
  File "/Applications/phenix/modules/cctbx_project/mmtbx/command_line/molprobity.py", line 155, in run
    out=out)
  File "/Applications/phenix/modules/cctbx_project/mmtbx/command_line/__init__.py", line 524, in __init__
    full_grm = self.model.get_restraints_manager()
  File "/Applications/phenix/modules/cctbx_project/mmtbx/model/model.py", line 895, in get_restraints_manager
    self.setup_restraints_manager()
  File "/Applications/phenix/modules/cctbx_project/mmtbx/model/model.py", line 1398, in setup_restraints_manager
    self._process_input_model()
  File "/Applications/phenix/modules/cctbx_project/mmtbx/model/model.py", line 1316, in _process_input_model
    use_neutron_distances     = self._pdb_interpretation_params.pdb_interpretation.use_neutron_distances)
  File "/Applications/phenix/modules/cctbx_project/mmtbx/utils/__init__.py", line 981, in __init__
    if(mon_lib_srv is None): self.mon_lib_srv = monomer_library.server.server()
  File "/Applications/phenix/modules/cctbx_project/mmtbx/monomer_library/server.py", line 419, in __init__
    cif_object=list_cif.cif, skip_comp_list=True)
  File "/Applications/phenix/modules/cctbx_project/mmtbx/monomer_library/server.py", line 429, in convert_all
    self.convert_deriv_list_dict(cif_object=cif_object)
  File "/Applications/phenix/modules/cctbx_project/mmtbx/monomer_library/server.py", line 443, in convert_deriv_list_dict
    deriv = cif_types.chem_comp_deriv(**dict(row))
  File "/Applications/phenix/modules/cctbx_project/mmtbx/monomer_library/cif_types.py", line 21, in __init__
    self._looped_ids = self.__class__.__doc__.split()
AttributeError: 'NoneType' object has no attribute 'split'
An exception  of type AttributeError occurred. Message:
("'NoneType' object has no attribute 'split'",)

**Comment by massyasha** [comment]
The error arises because cif_types constructor is trying to parse some cif properties from the docstring of the subclass. For example this one: <class 'mmtbx.monomer_library.cif_types.chem_comp_deriv'> . Now the problem is that docstring is None depending on how you run the code. I have read in fact that the python interpreter can optimize the code by stripping out the docstring. Maybe is not the safest way of reading that information.

**Comment by nwmoriarty** [comment]
Do you know how much improvement is achieved by stripping the docstrings from the files?

**Comment by massyasha** [comment]
Well, the pyc is lighter so in principle can be loaded faster, although to be honest, I do not think it will make so much difference. The reason why it could be a concern is that the configuration of the python interpreter is something out of control of the developer. In my case I am not explicitly running the code with the -OO flag (which strip the docstring) but still I am getting:

============================== Collecting inputs ==============================

Symmetry information was not found, putting molecule in P1 box.

                   ----------Processing PDB file(s)----------                  

----- <class 'mmtbx.monomer_library.cif_types.chem_comp_deriv'>
----- None


in the cctbx_project/mmtbx/monomer_library/cif_types.py 
it recognize correctly the class but the docstring is strangely None. It must be something with my configuration I am trying to dig out why I get this behavior.

**Comment by massyasha** [comment]
I tried many things but what it works for me was to modify the line:

self._looped_ids = self.__class__.__doc__.split()

into

self._looped_ids = self.__doc__.split()

This made trick for me.

**Comment by bkpoon** [comment]
Can you provide your `conda` environment? The output to `conda list -p <path to conda_base>` or `conda list -n <name of custom environment>`.

**Comment by massyasha** [comment]
[conda_info.txt](https://github.com/cctbx/cctbx_project/files/5044425/conda_info.txt)
<img width="255" alt="specs_os" src="https://user-images.githubusercontent.com/45395710/89698256-1bf98000-d918-11ea-8ed9-c330ee8bc967.png">

**Comment by massyasha** [comment]
Do you have any idea why I need to modify that line to make it work? The problem is that the docstrings are accessible only from self and self.__class__.   I am running my code using the phenix.python interpreter.  With the change in that line in my computer, it works both importing the mmtbx.command_line.molprobity in my code but also running phenix.molprobity from command line.

**Comment by bkpoon** [comment]
That's odd, I'm also running 10.15.6, and I don't get the error. Can you try creating a clean environment? It looks like you are using the cctbx environment, so just try
```
conda create -n new_phenix2 --file <modules directory>/cctbx_project/libtbx/auto_build/conda_envs/cctbx_py27_osx-64.txt
```
You should be able to swap the environment for your build without much issue with
```
conda activate new_phenix2
cd <directory with bootstrap.py and build directory>
python bootstrap.py build --use-conda $CONDA_PREFIX --builder <your builder>
```
To swap back, do the same thing, but activate your `phenix2` environment.

Do you get the same problem in Python 3? I just checked in general environment files for Python 3, so you can create an up-to-date environment with
```
conda env create -n new_phenix3 --file <modules directory>/cctbx_project/libtbx/auto_build/conda_envs/cctbx_osx-64.txt
```
You will want to do a new build since many dependencies will be different. You can specify a different build directory with
```
conda activate new_phenix3
cd <directory with bootstrap.py and build directory>
python bootstrap.py build --use-conda $CONDA_PREFIX --builder <your builder> --nproc <nproc> --build-dir py3_build
```
Since this is an up-to-date `conda-forge` environment, you can add your extra dependencies via `conda`.

The only differences I see between your working environment and mine are the extra dependencies from `pip`.

**Comment by massyasha** [comment]
new releases of cctbx does not present this problem for me anymore. Especially now that voyager is integrated within the phenix environment. So I will close the issue.
