### ISSUE TITLE
phil type "choice" doesn't behave as documented 

### ISSUE THREAD

**Issue by dwpaley** [cctbx/cctbx_project#531]
In the documentation for .type = choice: [http://cctbx.sourceforge.net/libtbx_phil.html#type-choice](url)

> To maximize convenience, especially for choices specified via the command-line, the `*` is optional if only one value is given. For example, the following two definitions are equivalent:

```
gender = female
gender = male *female
```

In reality:
```
> from libtbx.phil import parse
> no_star = "topping = mushroom\n  .type=choice"
> with_star = "topping = *mushroom\n  .type=choice"
> parse(no_star).extract().topping
> parse(with_star).extract().topping
['mushroom']

**Comment by bkpoon** [comment]
You need to use the rest of the code. I copied a basic example below
```
import sys
from libtbx.phil import parse

master_phil = parse("""
  gender = male female
    .type = choice
  favorite_sweets = ice_cream chocolate candy_cane cookies
    .type = choice(multi=True)
  """)

def run():
  choice_1 = parse("gender = female")
  choice_1_params = master_phil.fetch(source=choice_1).extract()
  print(choice_1_params.gender)

  choice_2 = parse("gender = male *female")
  choice_2_params = master_phil.fetch(source=choice_2).extract()
  print(choice_2_params.gender)

if __name__ == '__main__':
  sys.exit(run())
```

The `master_phil` defines the possible choices for `gender`. The user would provide the `working_phil` and those are two equivalent ways of setting the `gender` parameter. The `fetch` function is for matching the `working_phil` with the `master_phil` and getting the final set of parameters. One way to differentiate the two is that `master_phil` contains all the settings, defaults, and metadata (e.g. `.type`). The `working_phil` is what the user would provide.

**Comment by dwpaley** [comment]
ahhhhhh thanks a lot!
