### ISSUE TITLE
Provide more flex array types

### ISSUE THREAD

**Issue by dagewa** [cctbx/cctbx_project#532]
For data processing tasks, we have identified a need for coverage of some more C types, for example `flex.short` to mirror `flex.long`, and some short unsigned types. This issue is to discuss which types we need, and to decide on naming and any additional features before we set up a branch to create these. Assigning @graeme-winter as the originator of the request, but I suspect various others may have an interest.

**Comment by graeme-winter** [comment]
Assert - we should be precise in here e.g. `flex.uint16_t` etc.

Personally I would be happy to have the full gamut of fixed width int types even those which alias existing flex types e.g. `flex.int32` alongside `flex.int`

**Comment by graeme-winter** [comment]
Am exploring terrain in fixed-width-int-types branch

**Comment by graeme-winter** [comment]
I have implemented (or attempted to) `int8_t`, `int16_t`, and `int64_t` - seems to be a certain amount of overlap with existing implementations (`short` exists in some places etc.) 

Will down tools for the moment, need to add tests but first: is this the right direction?

**Comment by graeme-winter** [comment]
While I am here I note a `flex.size_t` is an unsigned 4 byte int, but should probably be a `uint64`
