### ISSUE TITLE
bootstrap.py from commit a088d9d39c3964ee38d9555f2310c7c0cedc4730 on master branch fails out of the box on Ubuntu 18.04

### ISSUE THREAD

**Issue by russell-taylor** [cctbx/cctbx_project#534]
I'm starting a project with the Richardson lab that will be working on integrating their tools more closely into the cctbx, including porting some of all of them to Python.

One of my first steps is to be able to build a cctbx development environment so that I can modify the source there and rebuild.

I really like the build instructions and build system, especially because it both pulls in all dependencies and also lists explicitly what it is doing.

When I ran 'python3 bootstrap.py' to make the repository, it pulled the sources and then ran into trouble during the installation of glib while building base.

This is on Ubuntu 18.04.5 LTS.  Python version 3.6.9.

Here's the error trace:

```
Installing glib...
  log file is /home/taylorr/rlab/base_tmp/glib_install_log
  getting package glib-2.46.2.tar.gz...
    downloading from http://cci.lbl.gov/cctbx_dependencies/glib-2.46.2.tar.gz : 14.1 MB
    [0%.........20%.........40%.........60%.........80%.........100%]
  installing glib-2.46.2.tar.gz...
Traceback (most recent call last):
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1682, in <module>
    installer(args=sys.argv, log=sys.stdout)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 256, in __init__
    self.build_dependencies(packages=packages)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 782, in build_dependencies
    getattr(self, 'build_%s'%i)()
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 1315, in build_glib
    log=pkg_log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 580, in configure_and_build
    self.call("make -j %d %s" % (nproc, " ".join(list(make_args))), log=log)
  File "modules/cctbx_project/libtbx/auto_build/install_base_packages.py", line 359, in call
    return call(args, log=log, verbose=self.verbose, **kwargs)
  File "/home/taylorr/rlab/modules/cctbx_project/libtbx/auto_build/installer_utils.py", line 55, in call
    raise RuntimeError("Call to '%s' failed with exit code %d" % (args, rc))
RuntimeError: Call to 'make -j 1 ' failed with exit code 2
Process failed with return code 1
```

**Comment by bkpoon** [comment]
You should use the the `--use-conda` flag for `bootstrap.py`. That skips the compilation of dependencies and uses `conda` packages instead. The command becomes,
```
python bootstrap.py --use-conda
```
To pick a specific version of `python` you can add the `--python` flag and the major/minor version without the dot (e.g. Python 3.8 is 38).
```
python bootstrap.py --use-conda --python 38
```
Lastly, add the `--builder` flag to pick a specific builder. The default is `cctbx`.

We should talk next week.

**Comment by russell-taylor** [comment]
Thank you!  You're at the top of my list of people to talk with already.  I think they are trying to set up a breakout session on Wednesday to talk about the project and make introductions.

I'll leave the issue open in case you want to use it as a reminder to change the defaults, the documentation, or to repair the non-conda path in the script.
