### ISSUE TITLE
Installation instructions missing

### ISSUE THREAD

**Issue by nonnominandus** [cctbx/cctbx_project#561]
I spent two full days installing cctbx, with some help of a coworker, because I stumbled upon some problems for which I think other people could be warned. I first tried installing it on Windows, which I rejected when I did not find sufficient help on installing. After this I found the bootstrap.py file here on Github and tried installing this on Ubuntu (WSL). 

Just running `python bootstrap.py` gives this error message.

```
Performing actions: hot update base build
Installing base packages using:
  python modules/cctbx_project/libtbx/auto_build/install_base_packages.py --python-shared --cctbx --cctbx --nproc=1 --
skip-if-exists
===== Downloading https://github.com/SCons/scons/archive/3.1.1.zip:  Traceback (most recent call last):
  File "bootstrap.py", line 2934, in <module>
    run()
  File "bootstrap.py", line 2929, in run
    no_boost_src=options.no_boost_src,
  File "bootstrap.py", line 1241, in run
    i.run()
  File "bootstrap.py", line 1507, in run
    use_ssh=use_git_ssh, verbose=True, reference=reference_repository_path)
  File "bootstrap.py", line 548, in git
    Toolbox.download_to_file(source_candidate, filename)
  File "bootstrap.py", line 351, in download_to_file
    f = open(tmpfile, 'wb')
IOError: [Errno 2] No such file or directory: 'modules/scons-3.1.1.zip.tmp'
```

After some time I figured out that it should be run using sudo `sudo python bootstrap.py`. Whici resulted in the following error.

```
In file included from /usr/local/cctbx/modules/dxtbx/format/boost_python/image_ext.cc:22:
/usr/local/cctbx/modules/dxtbx/format/tiff_reader.h:18:10: fatal error: tiffio.h: No such file or directory
   18 | #include <tiffio.h>
      |          ^~~~~~~~~~
compilation terminated.
```

Which I later figured out was because I did not have a library installed which apparently is required `sudo apt install libtiff-dev`. I found this by searching for the header file and one of the results talked about the package `libtiff`. With this package in place it finaly went smoothly. I hope that by posting this here I can help some people that stumble upon the same problems. If it is considered fitting these step could also be included in the instalation instructions.

**Comment by bkpoon** [comment]
There have been updates to the installation process which have not been reflected in the installation instructions. The major change is that you can get cctbx as a conda package from the conda-forge channel. On linux, macOS, or Windows, if you have `conda` installed either from the [full Anaconda installer](https://www.anaconda.com/products/individual) or from the [minimal installer](https://docs.conda.io/en/latest/miniconda.html), you can install cctbx into your currently active environment with
```
conda install -c conda-forge cctbx
```
or
```
conda install -c conda-forge cctbx-base
```
The only difference between the `cctbx` and `cctbx-base` packages is that `cctbx` also includes `wxpython`, `pyside2`, and `python`.

If you need to build from source, you can switch to using conda packages for dependencies which avoids having to compile them from source and is generally more compatible with newer operating systems. Your `bootstrap.py` command becomes
```
python bootstrap.py --use-conda
```
If an existing conda installation cannot be found, a `miniconda` installation will be created and the dependencies will exist in an environment located in the `conda_base` directory.

**Comment by nonnominandus** [comment]
Thanks a lot! This finally gave me the opportunity to access the toolbox from my own scripts.
