### ISSUE TITLE
RCSB PDB legacy API discontinuation

### ISSUE THREAD

**Issue by rjgildea** [cctbx/cctbx_project#562]
RCSB PDB legacy APIs are being discontinued in the very near future. In particular, any URL that starts with "rcsb.org/pdb" will be discontinued in December, as well as various other legacy APIs:
https://www.rcsb.org/news?year=2020&article=5f9714798807d067f8922116

The current recommended URLs for downloading are documented here:
https://www.rcsb.org/pages/download/http

There are a number of references to the legacy "rcsb.org/pdb" in the source code - some just in comments, but some are in actual code:
```
$ find . -name "*.py" -type f | xargs grep "rcsb.org/pdb"
./iotbx/bioinformatics/pdb_info.py:web_urls = {"rcsb": "http://www.rcsb.org/pdb/rest/customReport.xml?"+\
./iotbx/bioinformatics/pdb_info.py:  get_all = "http://www.rcsb.org/pdb/rest/customReport.xml?"+\
./iotbx/pdb/fetch.py:# http://www.rcsb.org/pdb/static.do?p=download/http/index.html
./iotbx/pdb/fetch.py:# PDB  uncompressed https://www.rcsb.org/pdb/files/2vz8.pdb
./iotbx/pdb/fetch.py:# CIF  uncompressed https://www.rcsb.org/pdb/files/2vz8.cif
./iotbx/pdb/fetch.py:# XML  uncompressed https://www.rcsb.org/pdb/files/2vz8.xml
./iotbx/pdb/fetch.py:# Data uncompressed https://www.rcsb.org/pdb/files/2vz8-sf.cif
./iotbx/pdb/fetch.py:# CIF  uncompressed https://www.rcsb.org/pdb/files/ligand/ATP.cif
./iotbx/pdb/fetch.py:      # url = "https://www.rcsb.org/pdb/download/downloadFastaFiles.do?structureIdList=%s&compressionType=uncompressed" % id
./iotbx/pdb/fetch.py:    url = "http://www.rcsb.org/pdb/files/ligand/%s.cif" % code
./mmtbx/wwpdb/rcsb_web_services.py:http://www.rcsb.org/pdb/software/rest.do
./mmtbx/wwpdb/rcsb_web_services.py:url_base = "http://www.rcsb.org/pdb/rest"
./mmtbx/wwpdb/rcsb_web_services.py:  url_base = "http://www.rcsb.org/pdb/rest/customReport?"
./wxtbx/reports/__init__.py:      url = "http://www.rcsb.org/pdb/explore/explore.do?structureId=%s" %pdb_id
```

**Comment by olegsobolev** [comment]
Thank you.

I have changed the code to use new API:

54c20794b4b66cbdb2796c37f27569802317e47d
fa87683e59e791cd23a9a4813ab6d111beb94a08
b01996262e49f28442d2aada90d73d6e24f27dbe

**Comment by Anthchirp** [comment]
Just a note that this introduces a dependency on `requests`, which will have to go in to https://github.com/conda-forge/cctbx-base-feedstock with the next update
@bkpoon

**Comment by bkpoon** [comment]
The current Python 3.9 builds will be fixed once the conda package cache is updated from a2d3973e0cde971833689bf93849100fabc0d02a. And the `2020.11` release will be updated.
