### ISSUE TITLE
Problems installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by jongablop** [cctbx/cctbx_project#569]
Hi,

I'm having some issues when trying to install cctbx. It raises the following error although ``future`` and ``six`` have been installed using pip. My machine is running Ubuntu 18.04 and I'm using Python 3.6.9.

```
$ python3 bootstrap.py
(...)
Base directory already exists and --skip-if-exists set; exiting.
===== Running in build: run configure.py

******************************************************************************
FATAL: For Python 2/3 compatibility, CCTBX currently requires the six and
  future modules.
To install, please use pip or conda (if available)
  pip install six future
  conda install six future
******************************************************************************
```

I think I could use conda to install cctbx but I'm interested in running ``iotbx`` inside ``virtualenv``. Is there any way to install it using ``pip``?

Thanks,

Jon

**Comment by bkpoon** [comment]
Hi Jon,

A `conda` environment is basically a `virtualenv` environment that supports non-Python packages so I would recommend using `conda` for more flexibility. You can install `pip` packages into a `conda` environment, but the `conda` version is preferred if it is available.

For this particular error message, was the `base` directory built recently? The `six` and `future` dependencies have to be in the Python that is available in `base`. You can also try deleting the `base` directory and re-running the command.

**Comment by jongablop** [comment]
Hi,

I finally migrated the whole proyect to a ``conda`` environment and the installation was straightforward. I assume that when installing by ``conda`` only Python packages are installed, am I wrong?

It would be nice to see the conda-based installation guide in the README. Do you want me to edit it and do a PR?

**Comment by bkpoon** [comment]
Great! I have been meaning to update the instructions and I just committed a change. Let me know if it's not clear. Thanks!
