### ISSUE TITLE
Python crash in Windows

### ISSUE THREAD

**Issue by dagewa** [cctbx/cctbx_project#591]
I have a Windows build of DIALS following these instructions: https://github.com/dials/dials/wiki/DIALS-on-Windows. I am seeing occasional problems between NumPy and flex. For example, this script

```
import numpy as np
from scitbx.array_family import flex

for i in range(2**31 - 1):
    print(i)
    flex.size_t((np.arange(i).astype(int)))
```
will crash the Python interpreter _at some point_, e.g. after printing `23665` in my most recent run.

Has this been seen before?

**Comment by dagewa** [comment]
This is also a problem with the Python 2.7 Windows build from `cctbx-installer-dev-2406-intel-windows-x86_64`, after swapping `range` for `xrange` in the above script. In my most recent run, this got to i=224, then crashed.

In this case, I have `Python 2.7.15 (default, Mar  5 2020, 14:56:45) [MSC v.1500 64 bit (AMD64)] on win32`, whereas the previous case has `Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)] on win32`.

This looks like a real issue with the numpy/scitbx bridge rather than a build or Python version issue.

**Comment by bkpoon** [comment]
I can confirm the issue with the `cctbx-base` conda package on Windows for Python 3.8. I can reproduce the crash with a large NumPy array with
```
import numpy as np
from scitbx.array_family import flex
n = np.arange(2**30).astype(int)
f = flex.size_t(n)
```
but using `flex.int` as a workaround will work.
```
import numpy as np
from scitbx.array_family import flex
n = np.arange(2**30).astype(int)
f = flex.int(n)
```
Then the `flex.int` array can be converted into `flex.size_t`, but that is an extra copy.

My Windows test machine only as 16 GB of memory, so I won't test an array of size 2^31-1, but I suspect the workaround should work. The `flex.size_t` and `flex.int` code is separate, so I'll look closer at why the behavior is different.

**Comment by dagewa** [comment]
Thanks Billy. The loop in the original test case was to test whether the failure was triggered at a particular size or if this varied. It turns out it varies, but always seemed "small", up to a few tens of thousand elements. Definitely no need to test arrays that approach all available memory!

**Comment by dagewa** [comment]
Thanks for looking at it @bkpoon. I'm still seeing this issue on my Windows build, and I realised the same thing is being triggered in dials/dials#1765

**Comment by bkpoon** [comment]
Yeah, sorry, I was too ambitious with that commit message. I am testing a more complete fix for the issue.

**Comment by bkpoon** [comment]
Commit 54350a068e0a111d4ce5f90f7edeb88f21040329 should work. The original implementation of the constructor with numpy arrays assumed that the types were the same (e.g. `numpy.int32` matches `flex.int`). I added the option to convert between types. However, complex types still need to match (`numpy.cdouble` matches `flex.complex_double`).

The segmentation fault was occurring because the `numpy.int` was being converted to a `flex.size_t` which involves changing the size of the type. I would still recommend that you match the types, though.

**Comment by dagewa** [comment]
Thanks Billy, I can confirm the fix :+1:
