### ISSUE TITLE
Move to UCS4

### ISSUE THREAD

**Issue by nwmoriarty** [cctbx/cctbx_project#60]
There are a number of reasons to enable UCS4 in all builds.

1. It's the current standard.
2. It's the standard in most UNIX OS releases.
3. I want to use the Mogul Python API which is UCS4, by default. 😎

**Comment by Anthchirp** [comment]
We had this in the past for a few months (Feb '16-Apr '16) until it was disabled by 4f59f3416802ef1533a4a116fc6f8291c9fcff17
I seem to recall that this caused some issues with Mac builds, too.
Switching between UCS2/4 also caused problems unless developers re-ran bootstrap from scratch.

**Comment by graeme-winter** [comment]
Looks like the absence of this is breaking things for my RHEL6 build of DIALs with 0MQ support - any chance could be revisited?
