### ISSUE TITLE
cctbx.xfel mpi_logger doesn't support debug logging

### ISSUE THREAD

**Issue by rjgildea** [cctbx/cctbx_project#606]
The `mpi_logger` in cctbx.xfel doesn't support the full logging interface:
* it doesn't support [`logger.debug`](https://docs.python.org/3/library/logging.html#logging.Logger.debug)
* it doesn't support `logger.info(msg, *args, **kwargs)`, i.e. valid used such as `logger.info("string_%s_%s", foo, bar)`

https://github.com/cctbx/cctbx_project/blob/f8b5de70cca3ff76c2253b5501835655735c8d7b/xfel/merging/application/mpi_logger.py#L60-L61

This means that `cctbx.xfel` is liable to break if upstream code introduces changes that use otherwise perfectly valid logging statements, e.g.:
https://github.com/dials/dials/pull/1647/files#diff-4eb0e90752ec0c5de32be735a2b55c490308091767055a97f52eb6315a7fac07R204-R206

**Comment by dwpaley** [comment]
Fixed by f7ce08b
