### ISSUE TITLE
Mac builds: don't embed absolute path in python executable

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#62]
no idea where/why this happens. The linux python executable does not contain an absolute path of where python was originally built. The mac python executable does.
This messes up relocation. To reproduce use a build _moved from the original build location_ and run
```
$ base/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import site; print site.getsitepackages()"
```
or
```
$ python -c "import site; print site.getsitepackages()"
```
On Linux this returns 2 absolute, relocated paths.
On Mac this returns 2 absolute, non-relocated paths.

**Comment by bkpoon** [comment]
There is an extra step for macOS that makes the paths relocatable. It is done when creating the binary installers. The function is in `libtbx/auto_build/rpath.py`. To manually run the step,
1. Create a copy (`<copy path>`) of the original build (`<original path>`)
2. `source <copy path>/build/setpaths_all.sh`
3. `libtbx.python <copy path>/modules/cctbx_project/libtbx/auto_build/rpath.py --otherroot <original path>/base <copy path>/base`
After a bunch of text, the <copy path> build will be relocatable. This command is done in the `copy_build` function in `libtbx/auto_build/create_installer.py`.
4. `libtbx.python -c "import site; print site.getsitepackages()"`
You should see the correct path now.

The `<copy path>` and `<original path>` should be full paths. Also, after step 3, you should be able to move the `<copy path>` build around without having to re-run step 3.

**Comment by Anthchirp** [comment]
Thank you, I did not know that.

Would you mind if I put
```
if macos and relocation_required:
  run_rpath oldbasepath newbasepath
```
into libtbx.configure?

**Comment by bkpoon** [comment]
Sure, you can add it to libtbx.configure. You should look at the `copy_dependencies` and `copy_build` functions in `libtbx/auto_build/create_installer.py`. Library files in the `build` directory may need to be updated as well.

**Comment by Anthchirp** [comment]
I've added the ```if``` bit, but not the actual relocation bit. First want to check this code is only run if the relocation is actually required. It should catch cases where the system python is used.
