### ISSUE TITLE
Windows build failure in nanoBragg

### ISSUE THREAD

**Issue by dagewa** [cctbx/cctbx_project#639]
I'm currently getting a failure while trying to build DIALS on Windows. The end of the build log states this:
```
C:\Users\fcx32934\sw\cctbx-build-test\modules\cctbx_project\simtbx\nanoBragg\nanoBragg_ext.cpp(31): note: while trying to match the argument list '(double)'
C:\Users\fcx32934\sw\cctbx-build-test\modules\cctbx_project\simtbx\nanoBragg\nanoBragg_ext.cpp(31): error C2660: 'boost::python::make_tuple': function does not take 4 arguments
c:\Users\fcx32934\sw\cctbx-build-test\conda_base\Library\include\boost/python/tuple.hpp(62): note: see declaration of 'boost::python::make_tuple'
scons: building terminated because of errors.
```
Curiously, the line in question,
https://github.com/cctbx/cctbx_project/blob/a47b4700fe1473e8296598c9f4a1c2544282a25e/simtbx/nanoBragg/nanoBragg_ext.cpp#L31
was modified 4 years ago in adb332f00e as part of fixes required for Windows builds

**Comment by ndevenish** [comment]
`nanobragg.h` was recently changed to remove a define around this though: https://github.com/cctbx/cctbx_project/commit/035859190d4776f7320696d235d8c7467a25ec68#diff-694ff3136456a7e95e00ac05cf34865638415ce208f85a67b27e7f1f5ecb5429

It looks like `simtbx` isn't tested on windows on the per-commit CI:
https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=15884&view=logs&j=350d36e3-5a1d-50ee-2c2a-e462502efd08&t=e88dbd25-6370-54e6-6229-33ea1e83fd77&l=44
