### ISSUE TITLE
Issue reading and validating CIF files

### ISSUE THREAD

**Issue by jongablop** [cctbx/cctbx_project#662]
Hi!

Recently I have been working on a web application to read and validate CIF files and I have noticed that the CIF model is not constructed as expected. Let me show you an example. Let's assume the following CIF file:

```
data_RbMo
_audit_block_code                 RbMo

_diffrn_ambient_temperature 200
_diffrn_ambient_temperature 300

loop_
   _atom_type_symbol
   Rb

loop_
  _atom_site_label
  _atom_site_type_symbol
  _atom_site_fract_x
  _atom_site_fract_y
  _atom_site_fract_z
  Rb1  Rb           0.5           0         0.25
  Rb2  Rb    0.31563(3)         0.5   0.14226(3)

loop_
  _atom_site_label
  _atom_site_U_iso_or_equiv
  Rb1 0.5(2)
  Rb2 0.5(3)

loop_
  _atom_site_Fourier_wave_vector_seq_id
  _atom_site_Fourier_wave_vector_x
  _atom_site_Fourier_wave_vector_y
  _atom_site_Fourier_wave_vector_z
  1  0  0.748  0

loop_
  _atom_site_displace_Fourier_id
  _atom_site_displace_Fourier_atom_site_label
  _atom_site_displace_Fourier_axis
  _atom_site_displace_Fourier_wave_vector_seq_id
  Rb1y1 Rb1  y  1
  Rb2x1 Rb2  x  1
  Rb2y1 Rb2  y  1
  Rb2z1 Rb2  z  1

loop_
  _atom_site_displace_Fourier_parm_id
  _atom_site_displace_Fourier_param_cos
  _atom_site_displace_Fourier_param_sin
  Rb1y1   -0.0043(3)           0
  Rb2x1            0  -0.0001(1)
  Rb2y1   -0.0027(2)           0
  Rb2z1            0   0.0001(1)
```

That CIF presents several errors. On the one hand, the tag `_diffrn_ambient_temperature` appears twice with different values. In my opinion, the CIF reader should read both tag-value pairs and then an error should be raised by the validator. On the other hand, this CIF presents a typo in tag `_atom_site_displace_Fourier_parm_id` (last loop). As a consecuence, the last two loops get the same identifier (which is the longest common substring in all the tags of a loop) and the second one is completely ignored.

This is the model obtained after reading the CIF:

```
data_RbMo
_audit_block_code                 RbMo
_diffrn_ambient_temperature       300
loop_
  _atom_type_symbol
  Rb

loop_
  _atom_site_label
  _atom_site_type_symbol
  _atom_site_fract_x
  _atom_site_fract_y
  _atom_site_fract_z
  Rb1  Rb         0.5    0        0.25
  Rb2  Rb  0.31563(3)  0.5  0.14226(3)

loop_
  _atom_site_Fourier_wave_vector_seq_id
  _atom_site_Fourier_wave_vector_x
  _atom_site_Fourier_wave_vector_y
  _atom_site_Fourier_wave_vector_z
  1  0  0.748  0

loop_
  _atom_site_displace_Fourier_id
  _atom_site_displace_Fourier_atom_site_label
  _atom_site_displace_Fourier_axis
  _atom_site_displace_Fourier_wave_vector_seq_id
  Rb1y1  Rb1  y  1
  Rb2x1  Rb2  x  1
  Rb2y1  Rb2  y  1
  Rb2z1  Rb2  z  1
```
As you will notice, the repeated tag and the 'repeated' loop are not present in the model.

As a possible solution, I think that loops should get an unique identifier that doesn't cause conflicts between similar loops and the presence of repeated tags should be checked while the CIF if being read.

**Comment by olegsobolev** [comment]
Hi Jon,

Can you please specify where you get such files from? I don't remember
coming across such examples. They do violate the CIF format. I agree that
we could probably handle this better, but maybe the program that produces
it should be fixed?

Oleg.

**Comment by olegsobolev** [comment]
I believe [iotbx/pdb/tst_mmcif.py](https://github.com/cctbx/cctbx_project/blob/master/iotbx/pdb/mmcif.py) contains couple of self-explanatory examples and seems to be an OK place to add a new test. In this case we would like to see Sorry raised, so the test would check for it much like in https://github.com/cctbx/cctbx_project/blob/c6f69d80f14658a5bac479d62daad2575b8d6fba/iotbx/pdb/tst_hierarchy.py#L2300-L2309

**Comment by olegsobolev** [comment]
Should be fixed with https://github.com/cctbx/cctbx_project/commit/ef172351008d551165024a54d3c6554216d7154a
