### ISSUE TITLE
bootstrap: update HDF5 filters

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#69]
bootstrap currently uses the lz4 library from https://github.com/dectris/HDF5Plugin, which is now a deprecated repository.
We should use https://github.com/nexusformat/HDF5-External-Filter-Plugins instead.
There is now a ```configure``` command in the ```LZ4``` directory, which is more useful than patching the Makefile.

**Comment by Anthchirp** [comment]
good news: ```bitshuffle``` is now in there as well.
bad news: the configure command is now gone and there are essentially no instructions on how to build it.

Guess we'll stick with the more ancient versions for the indeterminate future.

**Comment by ndevenish** [comment]
...it's built by CMake, so no configure? I've installed this in the past and I don't remember it being too complicated

**Comment by Anthchirp** [comment]
Well I can't get it to work. https://github.com/nexusformat/HDF5-External-Filter-Plugins/issues/8

**Comment by Anthchirp** [comment]
hm this could be an issue.
```
cd "hdf5_plugins"
cd "build"
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.0.0 or higher is required.  You are running version 2.8.12.2
```

**Comment by Anthchirp** [comment]
even more so:
```
$ ssh viper
$ cat /etc/centos-release 
CentOS release 6.9 (Final)
$ cmake
-bash: cmake: command not found
```

this will not end well.

**Comment by Anthchirp** [comment]
feel free to reopen if anyone wants to pick this up. assume this will be solved by conda move anyway.
