### ISSUE TITLE
Inconsistent definition of CUDAREAL

### ISSUE THREAD

**Issue by Trzs** [cctbx/cctbx_project#706]
NanobraggCUDA.h has 
```
#ifndef CUDAREAL
#define CUDAREAL float
#endif
```

diffBraggCUDA.h and diffBragg_gpu_kernel.h have
```
#ifndef CUDAREAL
#define CUDAREAL double
#endif
```

Which is correct? And are they needed, since SConscript uses "-DCUDAREAL=double"?

**Comment by nksauter** [comment]
We always need to be using double, but this is accomplished by the override
in SConscript.  The default in NanobraggCUDA.h is held over from James
Holton's work.

I do not believe anything needs to change, given all this.

Nick
