### ISSUE TITLE
Update Python to 2.7.14

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#72]
Changelog: https://raw.githubusercontent.com/python/cpython/84471935ed2f62b8c5758fd544c7d37076fe0fa5/Misc/NEWS

Any concerns?

**Comment by bkpoon** [comment]
No real concerns, but let me test the builds on our virtual machines before pushing the change.

**Comment by bkpoon** [comment]
There doesn't seem to be any new test failures with Python 2.7.14, so Python has been updated.

**Comment by Anthchirp** [comment]
thanks

**Comment by Oeffner** [comment]
http://scons.org/scons-300-is-available.html


Sent from my Windows 10 phone
-- 
Robert Oeffner, Ph.D.
Research Associate, The Read Group
Department of Haematology,
Cambridge Institute for Medical Research
University of Cambridge
Cambridge Biomedical Campus
Wellcome Trust/MRC Building
Hills Road
Cambridge CB2 0XY

www.cimr.cam.ac.uk/investigators/read/index.html
tel: +44(0)1223 763234
mobile: +44(0)7712 887162
