### ISSUE TITLE
CIF reader fails on PDB files

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#73]
Could not read mmcif files for PDB structures ```1ia0```, ```5q1h```, ```4y00```, ```4y0f```.
The other 133755 work fine.

**Comment by rjgildea** [comment]
1ia0 for example contains a unicode Angstrom symbol on line 1793:

> resolution (10Å) structure, which was published in EMBO J. 2006.

Only ascii characters are permitted:
https://www.iucr.org/resources/cif/spec/version1.1/cifsyntax#charset

> 22. Characters within a CIF are restricted to certain printable or white-space characters. Specifically, these are the ones located in the ASCII character set at decimal positions 09 (HT or horizontal tab), 10 (LF or line feed), 13 (CR or carriage return) and the letters, numerals and punctuation marks at positions 32-126.

**Comment by rjgildea** [comment]
```
$ iotbx.cif.validate 1ia0.cif 
CifParserError: 1ia0.cif(line 1793) : lexer error 3 :
	 at offset 15, near char(?) :
	Å) structure, which
```

**Comment by Anthchirp** [comment]
I think they are all caused by unicode. May well be true that standard prohibits this, but that doesn't change the files :)

**Comment by rjgildea** [comment]
So the solution is to inform the PDB that the files are incorrect, and then they will fix them.

**Comment by Anthchirp** [comment]
message passed on to wwPDB.
