### ISSUE TITLE
Default-constructed iotbx::pdb::hierarchy::atom has uninitiaized data->element values

### ISSUE THREAD

**Issue by russell-taylor** [cctbx/cctbx_project#763]
When an atom is statically defined in C++ on the stack using `iotbx::pdb::hierarchy::atom a;` in a function, the element values (and presumably some other values) are not initialized.  On Windows, they end up being filled with zeroes but on Linux they are filled with random values from the stack.

I noticed this in test code that fills in only some of the atom's values after constructing them because I only need some of them for the Probe2 calculations.  I've worked around this by explicitly setting all of the ones the code depends on, but this seems like it could cause trouble elsewhere.

**Comment by olegsobolev** [comment]
Thank you for bringing this to our attention. Although it might seem as a valid concern, we are reluctant to change this behavior for the following reasons:
- It is consistent with C behavior which does not initialize variables when you define them;
- It is not clear what default value would be appropriate for a general case (what is a general case?). E.g. setting 0 for coordinates will make an atom sit on a special position, 0 for B-factors is almost never the best value, element is a string of 2 characters which is even trickier and so on;
- It has been fine so far (14 years);
