### ISSUE TITLE
Installer does not work when only `python3` is available

### ISSUE THREAD

**Issue by dagewa** [cctbx/cctbx_project#788]
Comes from https://github.com/dials/dials/issues/2222; please see there for details

**Comment by bkpoon** [comment]
Is this the source installer or a binary installer? We had one Phenix user have a similar issue, but it was only for the source installer.

**Comment by ndevenish** [comment]
https://github.com/cctbx/cctbx_project/blob/fbe93bb4e5983c080b50e6f7973cce2f5f2ac6e8/libtbx/auto_build/create_installer.py#L34-L49
