### ISSUE TITLE
hklf.miller_array_export_as_shelx_hklf full_dynamic_range broken for some data values

### ISSUE THREAD

**Issue by dwpaley** [cctbx/cctbx_project#792]
@randyjread I have no familiarity with `%g` formatting so maybe you can see if something seems amiss? It seems that small numbers with a lot of digits (either positive or negative) cause the problem.

```
dwpaley@dials:/net/dials/raid1/dwpaley/ly65/c9/merging
$ cat repro.py
from cctbx import crystal
from dials.array_family import flex
from cctbx import miller
from iotbx.shelx import hklf
xs = crystal.symmetry((3,4,5), "P 2 2 2")
mi = flex.miller_index(((1,-2,3), (0,0,-4)))
ms = miller.set(xs, mi)
data = flex.double((.0001234567, 1))
ma = miller.array(ms, data)
hklf.miller_array_export_as_shelx_hklf(ma, full_dynamic_range=True)


dwpaley@dials:/net/dials/raid1/dwpaley/ly65/c9/merging
$ libtbx.python repro.py
Traceback (most recent call last):
  File "/net/dials/raid1/dwpaley/ly65/c9/merging/repro.py", line 10, in <module>
    hklf.miller_array_export_as_shelx_hklf(ma, full_dynamic_range=True)
  File "/dev/shm/dwpaley/20220829/modules/cctbx_project/iotbx/shelx/hklf.py", line 100, in miller_array_export_as_shelx_hklf
    line = fmt_3i4(h) + fmt_fullrange_data(data[i]*scale) + fmt_fullrange_sigma(s*scale)
  File "/dev/shm/dwpaley/20220829/modules/cctbx_project/iotbx/shelx/hklf.py", line 87, in fmt_fullrange_data
    assert len(result) == 8
AssertionError
```

**Comment by randyjread** [comment]
Hi,

Thanks for flagging this up! It’s obviously an unusual scenario, and clearly I didn’t test the full_dynamic_range option over a wide enough range of data. Interoperability between FORTRAN fixed formats and Python is a bit of a pain!

I’ve just committed and pushed a fix to cctbx_project, which changes two lines for formatting values with an absolute value less than 1, switching from g-format to f-format.

Best wishes,

Randy Read

> On 22 Sep 2022, at 21:56, Daniel Paley ***@***.***> wrote:
> 
> 
> @randyjread I have no familiarity with %g formatting so maybe you can see if something seems amiss? It seems that small numbers with a lot of digits (either positive or negative) cause the problem.
> 
> ***@***.***:/net/dials/raid1/dwpaley/ly65/c9/merging
> $ cat repro.py
> from cctbx import crystal
> from dials.array_family import flex
> from cctbx import miller
> from iotbx.shelx import hklf
> xs = crystal.symmetry((3,4,5), "P 2 2 2")
> mi = flex.miller_index(((1,-2,3), (0,0,-4)))
> ms = miller.set(xs, mi)
> data = flex.double((.0001234567, 1))
> ma = miller.array(ms, data)
> hklf.miller_array_export_as_shelx_hklf(ma, full_dynamic_range=True)
> 
> 
> ***@***.***:/net/dials/raid1/dwpaley/ly65/c9/merging
> $ libtbx.python repro.py
> Traceback (most recent call last):
>   File "/net/dials/raid1/dwpaley/ly65/c9/merging/repro.py", line 10, in <module>
>     hklf.miller_array_export_as_shelx_hklf(ma, full_dynamic_range=True)
>   File "/dev/shm/dwpaley/20220829/modules/cctbx_project/iotbx/shelx/hklf.py", line 100, in miller_array_export_as_shelx_hklf
>     line = fmt_3i4(h) + fmt_fullrange_data(data[i]*scale) + fmt_fullrange_sigma(s*scale)
>   File "/dev/shm/dwpaley/20220829/modules/cctbx_project/iotbx/shelx/hklf.py", line 87, in fmt_fullrange_data
>     assert len(result) == 8
> AssertionError
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 

-----
Randy J. Read
Department of Haematology, University of Cambridge
Cambridge Institute for Medical Research     Tel: +44 1223 336500
The Keith Peters Building                               Fax: +44 1223 336827
Hills Road                                                       E-mail: ***@***.***
Cambridge CB2 0XY, U.K.                              www-structmed.cimr.cam.ac.uk

**Comment by dwpaley** [comment]
Thank you! Looks good. I'll leave the option `--shelx_std_dynamic_range` available since it also makes the hkl file more human-readable...
Best,
Dan
