### ISSUE TITLE
Update Python syntax to be compatible with Python 2 and 3

### ISSUE THREAD

**Issue by bkpoon** [cctbx/cctbx_project#80]
* Use automated tools to update .py files
* Manually fix edge cases
* Test!

**Comment by Anthchirp** [comment]
cf. https://github.com/cctbx/cctbx_project/wiki/Python-3-roadmap

**Comment by Anthchirp** [comment]
will write to cctbxbb about required changes to libtbx_refresh.py to recommit this patch.

**Comment by Anthchirp** [comment]
Migrated [annlib_adaptbx](https://github.com/cctbx/annlib_adaptbx) to git so that I can distribute the required changes in that repository. Will send an email about that once I have the build working again.
