### ISSUE TITLE
update boost to 1.63 (nb #70)

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#82]

**Comment by Anthchirp** [comment]
Maybe use dials/boost repository for this, eventually move dials/boost to cctbx/boost.
Investigate forking that repo from the official repo, but have to make our own tags so that we can refer to defined versions and can reduce the download size (use @bkpoon's magic script)

**Comment by Anthchirp** [comment]
Disregard idea about using a forked official repo. The official repo uses submodules which aren't included in the github zip download link.

**Comment by ndevenish** [comment]
@bkpoon updated the LBL archive; thanks for this. Do we still want to be moving this over to using e.g. https://github.com/dials/boost?

**Comment by Anthchirp** [comment]
yes (but could be done in separate ticket, which can be assigned to myself)

**Comment by Anthchirp** [comment]
new issue created.
