### ISSUE TITLE
PyQt licensing question

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#83]
concerns re GPL

**Comment by graeme-winter** [comment]
potOfWorms.open()

**Comment by bkpoon** [comment]
Pyside2 (https://wiki.qt.io/PySide2) is further along than it was last year, so we should think about that instead of PyQt. It is actively supported by the Qt Company and it (and Qt) are licensed under LGPLv3.

**Comment by Anthchirp** [comment]
feel free to reopen if anyone wants to pick this up
