### ISSUE TITLE
libtbx: remove --old_division

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#86]
```libtbx.configure``` supports a flag ```--old_division``` which changes the libtbx default behaviour of running all python instances with ```-Qnew```, which is the equivalent of adding ```from __future__ import division``` to every file.

Given that we want to move to Python3, where this is the default division anyway, I do not see a need for a command line flag that goes backwards toward old Python 2.x behaviour. So I propose to remove ```--old_division```.

**Comment by bkpoon** [comment]
Yes, I agree. I don't see why we are supporting the old behavior if we're using the new behavior by default.

**Comment by ndevenish** [comment]
A cursory search seems to suggest that almost all of the cctbx_project files have division imported anyway. I can't imagine any scenario in which we'd want to explicitly allow the old behaviour. +1.
