### ISSUE TITLE
conda distribution?

### ISSUE THREAD

**Issue by hainm** [cctbx/cctbx_project#9]
hi,

is there any plan to build and distribute via [conda](http://conda.pydata.org/)? 
It's very popular now. We (AMBER) are thinking about distributing AmberTools binary via conda too.

**Comment by hainm** [comment]
uhm turns out that there `cctbx` via conda now. Not sure if it is official or not.

```bash
$ anaconda search cctbx
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     mw/cctbx                  | 20160224 | conda           | linux-64       
     mx/cctbx                  | 20160309 | conda           | linux-64, osx-64
```

**Comment by nwmoriarty** [comment]
How does a package get onto anacoda and why are there two?

**Comment by hainm** [comment]
> How does a package get onto anacoda

https://docs.continuum.io/anaconda-cloud/using

btw,  we (AMBER) are thinking about simple binary distribution as 
```bash
# proposed syntax only
conda install ambertools=17 -c http://ambermd.org/downloads
```

> why are there two

That means there are two users (I don't know them) with account `mw` and `mx` build `cctbx` and upload to their channels (given that `cctbx` LICENSE is quite permissive).
e.g: https://anaconda.org/mx/cctbx/files

**Comment by wojdyr** [comment]
Both packages were my experiments that are not continued.
More recently @luc-j-bourhis was looking into installing cctbx in pythonic way (not for conda, but more generally with distutils)

**Comment by Anthchirp** [comment]
There are conda packages available now, details in https://github.com/cctbx/cctbx_project/issues/451
For the first proper cctbx release see https://github.com/cctbx/cctbx_project/issues/515.
The plan is to get those releases into conda-forge, cf https://github.com/conda-forge/staged-recipes/pull/10021

**Comment by Anthchirp** [comment]
cctbx is now available in conda forge, see instructions in https://github.com/cctbx/cctbx_project/issues/530#issue-707572443
