### ISSUE TITLE
BuildBot will start to send emails about clutter

### ISSUE THREAD

**Issue by nwmoriarty** [cctbx/cctbx_project#91]
I have removed a large number of items deemed as clutter. Emails will start to fly from the GitHubPoller running on the Phenix BuildBot. I suggest a cleanup using libtbx.find_clutter over the next few days...

**Comment by Anthchirp** [comment]
Why send spam about this?

**Comment by graeme-winter** [comment]
Which repositories are you running this on?

```
Graemes-MacBook-Pro-5:cctbx_project graeme$ libtbx.find_clutter 

iotbx/pdb/extract_rfactors_resolutions_sigma.py: bare excepts=6
iota/components/iota_controls.py: unused imports=1
mmtbx/refinement/real_space/utils.py: bare excepts=1
dxtbx/__init__.py: unused imports=1
dxtbx/imageset.py: unused imports=1
dxtbx/tests/tst_image_readers.py: unused imports=1
dxtbx/tests/tst_imageset.py: unused imports=1
dxtbx/tests/model/experiment/tst_experiment_list.py: unused imports=2
dxtbx/model/detector_helpers.py: unused imports=1
dxtbx/format/FormatCBFFullPilatusDLS6MSN126.py: unused imports=1
dxtbx/format/image.py: unused imports=1

*** To clean up please use: libtbx.find_unused_imports_crude ***

  *** Please change bare excepts: ***
        Usually best:
          except Exception:
        Rarely necessary:
          except: # intentional
  

```

**Comment by graeme-winter** [comment]
Not touching first 3...

**Comment by graeme-winter** [comment]
@nwmoriarty would pre-commit hooks be a better way of doing this? i.e. you cannot make a push with clutter in it?

**Comment by graeme-winter** [comment]
@ndevenish I imagine you have an opinion on this also?

**Comment by Anthchirp** [comment]
I think pre-commit hooks much better suited for this, as that
* provides immediate feedback
* concerns only things you actually just touched (thus no diffusion of responsibility)
* doesn't annoy anyone else
* avoids "clean clutter" commits which clutter the project history (pet peeve)

We could modify the existing mechanism in libtbx.git_avoid_merges to install hooks (rename command as necessary) and run that as part of libtbx.configure so it is set up for everyone everywhere.

**Comment by nwmoriarty** [comment]
@graeme-winter This would be run on the cctbx_project like it was before it moved to GitHub. Of the first 3, the iota is not a Berkeley item but I'll take a look. 

Regarding pre-commit hooks, I've never used them so I'm not familiar with their clearly powerful features. I agree that it may be the way to go. Once they are in place we can close this Hawaiian delicacy...

**Comment by nwmoriarty** [comment]
@bkpoon

**Comment by Anthchirp** [comment]
Still unclear what the point of sending spam is. If find_clutter is important enough it should be run as a test. If it is not important enough to become a test then the mails don't serve a purpose either.

**Comment by Anthchirp** [comment]
git pre-commit hook can be set up by running ```libtbx.git_avoid_merges```.
I have not yet set this up to run as part of libtbx.configure, and am still waiting for feedback.

**Comment by nwmoriarty** [comment]
Can you summarise the features in the pre-commit hooks?

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by Anthchirp** [comment]
```libtbx.git_avoid_merges``` installs (approximately) this command into ```.git/hooks/pre-commit```:
```
exec git diff-index --check --cached HEAD --
```
which means that ```git commit``` no longer works unless the git internal whitespace checker is happy.
What the checker will complain about is defined by the [core.whitespace](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_code_core_whitespace_code) setting, and, unless it is overridden, this will be set on a per-repository-basis to ```blank-at-eol,space-before-tab,tab-in-indent,-blank-at-eof```. See the link for an explanation of the options.

Example in action:
```bash
$ echo "print 'ohai'    " > something.py
$ git add something.py
$ git status
# On branch master
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#	new file:   something.py
#
$ git commit -m "ohai"
something.py:1: trailing whitespace.
+print 'ohai'
$ git status
# On branch master
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#	new file:   something.py
#
```

**Comment by Anthchirp** [comment]
having thought about this for a while I don't think we should use commit hooks. They tend to get in the way and are annoying. When I want to commit a piece of code I want to commit it, and not care about code presentation issues that can be automated away. So I will remove the commit hook code again.

Similarly I don't care about this kind of code style warning. That might be different if one day we decide to actually define a common code style (presently this is not the case), but even then I would outsource the 'caring' bit to a Jenkins job to fix all white space issues in all files simultaneously once a week - instead of in 50 separate commits.

Either way there is nothing left to do in this ticket, so closing.
