### ISSUE TITLE
GUI crashed after trying to override the lock

### ISSUE THREAD

**Issue by wbhbc** [cctbx/cctbx_project#932]
I opened the phenix GUI a few days ago to check the refinement statistics and didn't run any job. Later on, the GUI seems not responding so I force quit it. After that, I tried to open the GUI again but every time it shows another session is running already and locked my project database. The prompt says I could override the lock. When I click yes, it returned a report saying python crashed.

<img width="540" alt="Screenshot 2023-10-11 at 10 44 08 PM" src="https://github.com/cctbx/cctbx_project/assets/57541619/1fb26d39-bde5-40fb-b402-2e56819d867f">

<img width="1112" alt="Screenshot 2023-10-11 at 10 44 15 PM" src="https://github.com/cctbx/cctbx_project/assets/57541619/56fa21e1-f3c0-4b6f-b62e-5e0e0f138f84">

This issue has been there for a couple of days and I restarted my laptop many times in between.
The PID of running session given in the prompt is not valid. I don't have such process running in the background.
I can still run phenix.refine from command line.
How could I solve this issue and run GUI again? Thank you!

**Comment by olegsobolev** [comment]
Hi,

If you recently updated to MacOS Sonoma, you can either get the latest nightly or patch your existing Phenix: https://phenix-online.org/pipermail/phenixbb/2023-October/025579.html

**Comment by wbhbc** [comment]
Thank you very much! It is solved.
