### ISSUE TITLE
Software name retrieval causes the mmcif parser to fail

### ISSUE THREAD

**Issue by aozalevsky** [cctbx/cctbx_project#937]
The attempt to retrieve the refinement software name from mmCIF files:

https://github.com/cctbx/cctbx_project/blob/a6ee7226b24817752953f2047a15b906be3c1390/iotbx/pdb/mmcif.py#L502C1-L503C1

Fails on files without one:

```
  File "/opt/molprobity/modules/cctbx_project/iotbx/pdb/mmcif.py", line 502, in get_program_name
    if i >= 0: return software_name[i]
TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```
According to the [dictionary](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Categories/software.html) neither the refinement software nor the software category is required to be present in a valid PBDx/mmCIF file.  

For instance, this causes Molprobity (which relies on the cctbx) to fail on totally valid RCSB PDB or PDB-DEV files.

**Comment by olegsobolev** [comment]
Thanks for pointing this out. Fixed: https://github.com/cctbx/cctbx_project/commit/df5275df66dbcba658658f16a482ece663a278a5 .
