### ISSUE TITLE
libtbx.obfuscate

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#94]
the command libtbx.obfuscate used anywhere? I could not find any reference anywhere, apart from:

* phenix/phenix/utilities/phenix_list_help.py (where it is mentioned as part of an ignore list)
* phenix_regression/wizards/command_line_tests/test_commands/test_commands.expected_output (where it seems to be just listed as command, without any consequence)

It does not appear to be very useful. Unless anybody wants to keep it around I would like to retire it.

**Comment by pafonine** [comment]
I'm all for removing code that is obsolete or useless. Less code - less 
maintenance.
Pavel
