### ISSUE TITLE
update numpy

### ISSUE THREAD

**Issue by Anthchirp** [cctbx/cctbx_project#95]
Any concerns going from 1.8.1 (March '14) to something more recent?

Proposal:
Step 1: change installation to use pypi (testing patch now)
Step 2: update version (in the future, unless objections)

for reference: potential intermediate versions are 1.8.2, 1.9.3, 10.10.4, 1.11.3, 1.12.1

**Comment by bkpoon** [comment]
I tried updating numpy to 1.10 or 1.11 a year or two ago and got a lot of test failures that looked like something broke instead of just slight differences in results. I didn't have time to solve the issue, so I didn't upgrade.

If the upgrade is simple with the latest version (1.13), sure, let's upgrade, but if some more fundamental changes are needed, let's wait until after the Phenix release. I'll also have time to help then.

**Comment by Anthchirp** [comment]
I'll have a look into it locally if I can see anything going wrong. Do you remember which package had problems?

**Comment by bkpoon** [comment]
I don't quite remember, but I think it had something to do with arrays.

**Comment by Anthchirp** [comment]
I ran 1.9.3 and 1.10.4 and observed no tests failing in our land. I can't say anything about phenix tests because for me >300 of them always fail...

**Comment by Anthchirp** [comment]
Updated to the last bugfix release of 1.8, which incidentally is the minimum version requirement of current scipy. I'll change our local builds to run with 1.13 over the weekend and see if anything breaks.

**Comment by phyy-nx** [comment]
The current build fails:

libtbx.run_tests_parallel module=dials nproc=32

Error:
    OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
    OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 2066296 max
    ImportError: numpy.core.multiarray failed to import

Speculation:
New version of numpy installed by pip (see 01a019277c93df10a4fff2cf6e46b55a4a56d26e) has OpenMP enabled somewhere (possibly OpenBLAS?).  This causes too many processes to start which crashes the tests.

Evidence:

Case 1
libtbx.run_tests_parallel module=dials nproc=4 # runs fine

Case 2
export OMP_NUM_THREADS=1
libtbx.run_tests_parallel module=dials nproc=32 # runs fine

Case 3
ulimit -u 16384 # default is 1024
libtbx.run_tests_parallel module=dials nproc=64 # runs fine

Note, we don't see this on our buildbot nodes.

**Comment by Anthchirp** [comment]
Since threads count as lightweight processes towards the process limit, and the number of threads [defaults to the number of CPUs](https://gcc.gnu.org/onlinedocs/libgomp/OMP_005fNUM_005fTHREADS.html) a limit of 1024 is already exceeded by having 32 instances running 32 threads each (32*33 = 1056). With a limit of 1024 this should not come as a surprise...

Apart from [raising the limit from 1024](https://rudametw.github.io/blog/posts/2014.04.10/not-enough-threads.html) I would suggest setting OMP_NUM_THREADS=1 within libtbx.run_tests_parallel unless nproc==1 or OMP_NUM_THREADS is already set. What do you think?

**Comment by phyy-nx** [comment]
I'm trying to understand what's going on.  I'm worried if other
multiprocess programs would hit this problem, like dials.stills_process,
cxi.merge, or dials.integrate.  I checked dials.stills_process with
nproc-64 and it's fine.  So is there something going on with how
libtbx.run_tests_parallel uses libtbx.easy_run to spawn 64 processes that
is the issue?

**Comment by Anthchirp** [comment]
I was unable to trigger the condition on my machine, but I would suspect that
* ```libtbx.run_tests_parallel``` runs *n* instances of separate, independent python processes
* which have no idea about other python processes running
* which is still equivalent to python multiprocessing
* so would expect the same issue to appear if OpenMP is used within python ```multiprocessing``` code.

What's worse: Since this is a per-user OS limit this will also hit you if you run completely separate instances of the code in separate terminal windows...

If you can reproducibly trigger it on your machine, could you have a look whether [```export OPENBLAS_NUM_THREADS=1```](https://github.com/xianyi/OpenBLAS#set-the-number-of-threads-with-environment-variables) makes a difference?

**Comment by phyy-nx** [comment]
Right, the whole thing makes me nervous since regular python
multiprocessing should trigger this but it isn't (at least using
dials.stills_process which uses libtbx.easy_mp).  If you'd like to
reproduce the error, use viper.lbl.gov (cci credentials) and create a build
at /net/viper/raid1/<username>.  Then use libtbx.run_tests_parallel
module=dials nproc=32.  You'll get the OpenBLAS error.

Using export OPENBLAS_NUM_THREADS=1 made the error disappear and the tests
run.

-Aaron

**Comment by bkpoon** [comment]
Can we revert the change to use the old way of building numpy? We're finalizing the Phenix release and I don't want users to get this problem. I checked that numpy version 1.8.1 from pypi also exhibits the issue.

**Comment by Anthchirp** [comment]
You are not releasing Phenix from a branch? Daring :)
Exploring a workaround now, if that doesn't work around will revert until release is out.

**Comment by Anthchirp** [comment]
I have set it up so that numpy is pulled in source form and compiled locally. This should be equivalent to the way it was done previously.

However. I am fairly confident that this does not solve the underlying issue. I fear that this only solves the issue for our machines because we do not have certain versions of libraries in certain places. Judging from [official numpy build files](https://github.com/numpy/numpy/blob/master/.appveyor.yml) there is nothing they do differently in the actual build step.

So please have a look whether this _"solution" "solves"_ the issue, but I hold that for a real solution we still should disable multithreading in tests. We could predicate this on the detection of a low process_limit.

**Comment by bkpoon** [comment]
The solution is working so far. This also might be a distribution/compiler/libgomp specific problem since we've only seen this on CentOS 6 (gcc 4.4.7). Also, this might have been the issue I saw a few years ago since it's on the same machine I do initial testing for dependency updates.

**Comment by Anthchirp** [comment]
So what needs to be done so we can go back to official numpy builds?
Seems like setting OPENBLAS=1 in libtbx.run_tests_parallel would do the trick.

**Comment by Anthchirp** [comment]
Testing this now on viper.

**Comment by Anthchirp** [comment]
(side note: we have used 1.13.3 for a couple of months now at DLS without any issues)

**Comment by Anthchirp** [comment]
```
libtbx.run_tests_parallel module=dials nproc=32
(..)
Running 219 tests on 32 processors:
(..)
Summary:
  Tests run                    : 219
  Failures                     : 0
  Warnings (possible failures) : 0
  Stderr output (discouraged)  : 0
```
ran it twice, so unless there are other tests failing I'd like to call this a success.
