### ISSUE TITLE
cluster.unit_cell does not work given only experiments.json files

### ISSUE THREAD

**Issue by rjgildea** [cctbx/cctbx_project#96]
For some reason cluster.unit_cell does not work given only experiments.json files (i.e. no integrated.pickles). I would have thought (perhaps naively?) that unit cell clustering should not require reflection data...

```
$ find. -name "*experiments.json" | xargs cluster.unit_cell --dials --paths
/dls/mx-scratch/rjgildea/software/cctbx/base/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/dls/mx-scratch/rjgildea/software/cctbx/base/lib/python2.7/site-packages/numpy/core/_methods.py:73: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/dls/mx-scratch/rjgildea/software/cctbx/base/lib/python2.7/site-packages/numpy/core/_methods.py:135: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/dls/mx-scratch/rjgildea/software/cctbx/base/lib/python2.7/site-packages/numpy/core/_methods.py:105: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/dls/mx-scratch/rjgildea/software/cctbx/base/lib/python2.7/site-packages/numpy/core/_methods.py:125: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
Gtk-Message: Failed to load module "canberra-gtk-module"
INFO cluster.ab_cluster: Hierarchical clustering of unit cells
INFO cluster.ab_cluster: Using Andrews-Bernstein distance from Andrews & Bernstein J Appl Cryst 47:346 (2014)
Traceback (most recent call last):
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/cctbx_project/xfel/clustering/command_line/cluster_unit_cell.py", line 67, in <module>
    run(args)
  File "/dls/mx-scratch/rjgildea/software/cctbx/build/../modules/cctbx_project/xfel/clustering/command_line/cluster_unit_cell.py", line 35, in run
    doplot=_args.noplot)
  File "/dls/mx-scratch/rjgildea/software/cctbx/modules/cctbx_project/xfel/clustering/cluster.py", line 466, in ab_cluster
    metric=lambda a, b: NCDist(a, b))
  File "/dls/mx-scratch/rjgildea/software/cctbx/base/lib/python2.7/site-packages/scipy/spatial/distance.py", line 1647, in pdist
    raise ValueError('A 2-dimensional array must be passed.')
ValueError: A 2-dimensional array must be passed.

```

**Comment by idyoung** [comment]
There's a mish-mash of things that aren't necessary for sorting by unit cell per se but would be necessary for some of the other functions Cluster has available. I suspect these could be separated out and made individually inaccessible when the reflection data are not available. Currently the SingleFrame constructor fails without reflection data, but the SingleDialsFrame and SingleDialsFrameFromFiles constructors, which call this constructor as well, could be fleshed out independently instead.

**Comment by phyy-nx** [comment]
Hi, I can get it to work like this:

cluster.unit_cell  ../*0_indexed* ../*0_refined* --dials --paths

Cluster_id       N_xtals
cluster_1        198

<snip>

-Aaron

**Comment by rjgildea** [comment]
It would be useful if it would run without the need to specify the reflection files, since I don't believe it is actually using them at all for the unit cell clustering (please correct me if I'm wrong). For example here at Diamond we only save the experiments.json files for autoprocessed data (for reasons of disk space we don't save all of the intermediate output of data processing from xia2).

It would also be potentially useful to create a dials.unit_cell_clustering command that is more similar to other dials commands (e.g. using the dials option parser, etc.).

**Comment by nksauter** [comment]
Richard,

I'm looking at cluster.unit_cell currently as an ongoing project and would
like to help.  Could you tar up your directory of JSON files and allow me
to give it a go?  If it doesn't work out of the box I may have some
uncommitted code that does the job.

Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by rjgildea** [comment]
Running the following command reproduced the error above:
`$ cluster.unit_cell *.json --dials --path`
When also passing the integrated.pickle files (not included in attachment) the command runs successfully.
[experiments.tar.gz](https://github.com/cctbx/cctbx_project/files/1483673/experiments.tar.gz)

**Comment by nksauter** [comment]
Fixed by adding a new option to take JSON-only input:
$ cluster.unit_cell *.json --json --path

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713
