### ISSUE TITLE
gltbx: Windows failure with Python => 3.8

### ISSUE THREAD

**Issue by bkpoon** [cctbx/cctbx_project#979]
On Windows, there is an issue with loading the `gltbx` extensions in Python 3.8 and greater. Python 3.7 is not affected.

This is probably due to the change in DLL resolution starting with Python 3.8 (https://github.com/python/cpython/issues/80266). The easiest solution is to migrate to `pyopengl` instead of debugging DLL resolution issues. One consequence is that OpenGL functions from `pyopengl` do not have keyworded arguments, so the keywords will have to be removed (but keep the arguments).

@dagewa Is it possible to add `pyopengl` as a dependency to CCP4?

**Comment by dagewa** [comment]
I should think that will be fine. I'll pass on the request, thanks.
